"""
Management command para cargar empresas mixtas con todos los campos completos
"""
from django.core.management.base import BaseCommand
from django.db import transaction
from apps.empresas.models import (
    Empresa, TipoEmpresa, Rubro, SubRubro, 
    ProductoEmpresaMixta, ServicioEmpresaMixta, PosicionArancelaria
)
from apps.core.models import Usuario, RolUsuario
from apps.geografia.models import Departamento, Municipio, Localidad
import random
from decimal import Decimal
import json

# Datos de empresas reales argentinas que venden productos Y ofrecen servicios
EMPRESAS_MIXTAS = [
    {
        'razon_social': 'TECHNISYS S.A.',
        'nombre_fantasia': 'Technisys',
        'tipo_sociedad': 'Sociedad Anónima',
        'cuit': '30500018351',
        'direccion': 'Av. Corrientes 222, Piso 10',
        'codigo_postal': 'C1043',
        'direccion_comercial': 'Av. Corrientes 222, CABA',
        'codigo_postal_comercial': 'C1043',
        'telefono': '+541143213000',
        'correo': 'contacto@technisys.com',
        'sitioweb': 'https://www.technisys.com',
        'instagram': '@technisys',
        'facebook': 'Technisys',
        'linkedin': 'technisys',
        'geolocalizacion': '-34.603722,-58.381592',  # Buenos Aires
        'descripcion': 'Empresa líder en soluciones de tecnología financiera, desarrollando software bancario y ofreciendo servicios de consultoría.',
        'observaciones': 'Empresa que combina productos de software con servicios de implementación y consultoría.',
        'exporta': 'Sí',
        'destinoexporta': 'Estados Unidos, Brasil, México, Colombia, Chile, España',
        'tipoexporta': 'Directa',
        'importa': False,
        'certificadopyme': False,
        'certificaciones': 'ISO 9001, ISO 27001, PCI DSS, SOC 2',
        'idiomas_trabaja': 'Español, Inglés, Portugués',
        'promo2idiomas': True,
        'participoferianacional': True,
        'feriasnacionales': 'Fintech Summit 2023, Banking Technology 2023',
        'participoferiainternacional': True,
        'feriasinternacionales': 'Money 20/20 2023 (EEUU), Fintech Americas 2023 (México)',
        'contacto_principal_nombre': 'Germán Pugliese',
        'contacto_principal_cargo': 'CEO',
        'contacto_principal_telefono': '+541143213000',
        'contacto_principal_email': 'gpugliese@technisys.com',
        'contacto_secundario_nombre': 'María Soledad Fernández',
        'contacto_secundario_cargo': 'Chief Operating Officer',
        'contacto_secundario_telefono': '+541143213001',
        'contacto_secundario_email': 'mfernandez@technisys.com',
        'productos': [
            {'nombre': 'Core Banking Platform', 'posicion_arancelaria': '8523.49.00', 'descripcion': 'Plataforma de banca digital completa', 'capacidad': 100, 'unidad': 'un'},
            {'nombre': 'Mobile Banking App', 'posicion_arancelaria': '8523.49.00', 'descripcion': 'Aplicación móvil de banca digital', 'capacidad': 500, 'unidad': 'un'},
            {'nombre': 'Payment Gateway', 'posicion_arancelaria': '8523.49.00', 'descripcion': 'Pasarela de pagos online', 'capacidad': 200, 'unidad': 'un'},
            {'nombre': 'Digital Wallet', 'posicion_arancelaria': '8523.49.00', 'descripcion': 'Billetera digital', 'capacidad': 300, 'unidad': 'un'},
            {'nombre': 'API Banking Suite', 'posicion_arancelaria': '8523.49.00', 'descripcion': 'Suite de APIs para servicios bancarios', 'capacidad': 150, 'unidad': 'un'},
        ],
        'servicios': [
            {
                'nombre': 'Implementación de Core Banking',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Servicios de implementación y configuración de plataforma bancaria',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Brasil, México, Colombia, Chile, España',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'ISO 27001, PCI DSS',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Consultoría Fintech',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Asesoramiento estratégico en transformación digital bancaria',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Brasil, México, Colombia',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'PMP, Agile',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Soporte Técnico 24/7',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Servicio de soporte técnico continuo para plataformas bancarias',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Brasil, México, Colombia, Chile',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'mensual',
                'certificaciones_tecnicas': 'ITIL, ISO 20000',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Capacitación en Banca Digital',
                'tipo_servicio': 'capacitacion',
                'descripcion': 'Programas de capacitación para equipos bancarios',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Brasil, México, Colombia, Chile',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Educación Corporativa',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Migración de Datos Bancarios',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Servicios de migración de datos entre sistemas bancarios',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Brasil, México, Colombia',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Data Migration Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
        ],
        'actividades_promocion': [
            {'tipo': 'feria', 'lugar': 'Money 20/20, Las Vegas, EEUU', 'anio': '2023', 'observaciones': 'Stand principal, 200m²'},
            {'tipo': 'feria', 'lugar': 'Fintech Americas, Ciudad de México, México', 'anio': '2023', 'observaciones': 'Participación con productos premium'},
            {'tipo': 'mision', 'lugar': 'São Paulo, Brasil', 'anio': '2023', 'observaciones': 'Misión comercial con bancos'},
            {'tipo': 'mision', 'lugar': 'Madrid, España', 'anio': '2022', 'observaciones': 'Expansión en mercado europeo'},
            {'tipo': 'ronda', 'lugar': 'Buenos Aires, Argentina', 'anio': '2023', 'observaciones': 'Ronda de negocios con instituciones financieras'},
            {'tipo': 'ronda', 'lugar': 'Córdoba, Argentina', 'anio': '2022', 'observaciones': 'Ronda de negocios ProCórdoba'},
        ],
        'departamento_nombre': 'Capital',
        'provincia_nombre': 'Buenos Aires',
    },
    {
        'razon_social': 'DON SATUR S.A.',
        'nombre_fantasia': 'Don Satur',
        'tipo_sociedad': 'Sociedad Anónima',
        'cuit': '30500018352',
        'direccion': 'Ruta Nacional 9 Km 170',
        'codigo_postal': 'X5152',
        'direccion_comercial': 'Ruta Nacional 9 Km 170, Arroyito, Córdoba',
        'codigo_postal_comercial': 'X5152',
        'telefono': '+543543457000',
        'correo': 'contacto@donsatur.com.ar',
        'sitioweb': 'https://www.donsatur.com.ar',
        'instagram': '@donsatur',
        'facebook': 'DonSatur',
        'linkedin': 'don-satur',
        'geolocalizacion': '-31.420083,-63.049619',  # Arroyito, Córdoba
        'descripcion': 'Empresa líder en producción de alimentos y servicios de catering para eventos corporativos.',
        'observaciones': 'Empresa que combina producción de alimentos con servicios de catering y eventos.',
        'exporta': 'Sí',
        'destinoexporta': 'Brasil, Chile, Uruguay, Paraguay, Estados Unidos',
        'tipoexporta': 'Mixta',
        'importa': True,
        'certificadopyme': False,
        'certificaciones': 'ISO 9001, ISO 14001, HACCP, BRC',
        'idiomas_trabaja': 'Español, Inglés, Portugués',
        'promo2idiomas': True,
        'participoferianacional': True,
        'feriasnacionales': 'Expoagro 2023, La Rural 2023, Expo Alimentaria 2023',
        'participoferiainternacional': True,
        'feriasinternacionales': 'Anuga 2023 (Alemania), SIAL 2023 (Francia)',
        'contacto_principal_nombre': 'Roberto Martínez',
        'contacto_principal_cargo': 'Director General',
        'contacto_principal_telefono': '+543543457000',
        'contacto_principal_email': 'rmartinez@donsatur.com.ar',
        'contacto_secundario_nombre': 'Ana Fernández',
        'contacto_secundario_cargo': 'Gerente de Exportaciones',
        'contacto_secundario_telefono': '+543543457001',
        'contacto_secundario_email': 'afernandez@donsatur.com.ar',
        'productos': [
            {'nombre': 'Alfajores Don Satur', 'posicion_arancelaria': '1905.90.00', 'descripcion': 'Alfajores de dulce de leche', 'capacidad': 20000, 'unidad': 'kg'},
            {'nombre': 'Galletas Suritdas', 'posicion_arancelaria': '1905.31.00', 'descripcion': 'Galletas surtidas', 'capacidad': 15000, 'unidad': 'kg'},
            {'nombre': 'Snacks Saludables', 'posicion_arancelaria': '1904.10.00', 'descripcion': 'Snacks saludables sin azúcar', 'capacidad': 10000, 'unidad': 'kg'},
            {'nombre': 'Barras de Cereal', 'posicion_arancelaria': '1904.10.00', 'descripcion': 'Barras de cereal energéticas', 'capacidad': 12000, 'unidad': 'kg'},
            {'nombre': 'Productos Sin TACC', 'posicion_arancelaria': '1905.19.00', 'descripcion': 'Productos sin gluten', 'capacidad': 8000, 'unidad': 'kg'},
        ],
        'servicios': [
            {
                'nombre': 'Catering para Eventos',
                'tipo_servicio': 'culturales_eventos',
                'descripcion': 'Servicios de catering para eventos corporativos y sociales',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'HACCP, Manipulación de Alimentos',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Consultoría en Alimentación',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Asesoramiento en desarrollo de productos alimenticios',
                'sector_atendido': 'agroindustria',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'ISO 9001, HACCP',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Desarrollo de Productos Personalizados',
                'tipo_servicio': 'investigacion_desarrollo',
                'descripcion': 'Desarrollo de productos alimenticios personalizados para clientes',
                'sector_atendido': 'agroindustria',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, Chile',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'I+D Alimentario',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Capacitación en Manipulación de Alimentos',
                'tipo_servicio': 'capacitacion',
                'descripcion': 'Cursos de capacitación en manipulación segura de alimentos',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Instructor Certificado',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Servicios de Empaque y Logística',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Servicios de empaque personalizado y logística para exportación',
                'sector_atendido': 'agroindustria',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, Chile, Uruguay',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'ISO 9001, Logística',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
        ],
        'actividades_promocion': [
            {'tipo': 'feria', 'lugar': 'Anuga, Colonia, Alemania', 'anio': '2023', 'observaciones': 'Stand de 150m²'},
            {'tipo': 'feria', 'lugar': 'SIAL, París, Francia', 'anio': '2023', 'observaciones': 'Participación con productos premium'},
            {'tipo': 'mision', 'lugar': 'São Paulo, Brasil', 'anio': '2023', 'observaciones': 'Misión comercial con distribuidores'},
            {'tipo': 'mision', 'lugar': 'Santiago, Chile', 'anio': '2022', 'observaciones': 'Expansión en mercado chileno'},
            {'tipo': 'ronda', 'lugar': 'Buenos Aires, Argentina', 'anio': '2023', 'observaciones': 'Ronda de negocios con compradores internacionales'},
            {'tipo': 'ronda', 'lugar': 'Córdoba, Argentina', 'anio': '2022', 'observaciones': 'Ronda de negocios ProCórdoba'},
        ],
        'departamento_nombre': 'San Justo',
        'provincia_nombre': 'Córdoba',
    },
    {
        'razon_social': 'TECNOLOGIA Y SERVICIOS INTEGRALES S.A.',
        'nombre_fantasia': 'TSI',
        'tipo_sociedad': 'Sociedad Anónima',
        'cuit': '30500018353',
        'direccion': 'Av. Santa Fe 2727',
        'codigo_postal': 'C1425',
        'direccion_comercial': 'Av. Santa Fe 2727, CABA',
        'codigo_postal_comercial': 'C1425',
        'telefono': '+541147893000',
        'correo': 'contacto@tsi.com.ar',
        'sitioweb': 'https://www.tsi.com.ar',
        'instagram': '@tsiargentina',
        'facebook': 'TSIArgentina',
        'linkedin': 'tsi-argentina',
        'geolocalizacion': '-34.571389,-58.437778',  # Buenos Aires
        'descripcion': 'Empresa de tecnología que desarrolla software y ofrece servicios de consultoría e implementación.',
        'observaciones': 'Empresa que combina productos de software con servicios de implementación.',
        'exporta': 'Sí',
        'destinoexporta': 'Brasil, Chile, Uruguay, Estados Unidos, España',
        'tipoexporta': 'Directa',
        'importa': False,
        'certificadopyme': True,
        'certificaciones': 'ISO 9001, CMMI Level 3',
        'idiomas_trabaja': 'Español, Inglés, Portugués',
        'promo2idiomas': True,
        'participoferianacional': True,
        'feriasnacionales': 'Argentina IT 2023, Digital Transformation Summit 2023',
        'participoferiainternacional': True,
        'feriasinternacionales': 'Gartner IT Symposium 2023 (EEUU)',
        'contacto_principal_nombre': 'Carlos Rodríguez',
        'contacto_principal_cargo': 'CEO',
        'contacto_principal_telefono': '+541147893000',
        'contacto_principal_email': 'crodriguez@tsi.com.ar',
        'contacto_secundario_nombre': 'Laura Sánchez',
        'contacto_secundario_cargo': 'Gerente de Ventas',
        'contacto_secundario_telefono': '+541147893001',
        'contacto_secundario_email': 'lsanchez@tsi.com.ar',
        'productos': [
            {'nombre': 'ERP Empresarial', 'posicion_arancelaria': '8523.49.00', 'descripcion': 'Sistema ERP completo para empresas', 'capacidad': 50, 'unidad': 'un'},
            {'nombre': 'CRM Cloud', 'posicion_arancelaria': '8523.49.00', 'descripcion': 'Sistema CRM en la nube', 'capacidad': 200, 'unidad': 'un'},
            {'nombre': 'Software de Facturación', 'posicion_arancelaria': '8523.49.00', 'descripcion': 'Sistema de facturación electrónica', 'capacidad': 300, 'unidad': 'un'},
            {'nombre': 'Plataforma E-commerce', 'posicion_arancelaria': '8523.49.00', 'descripcion': 'Plataforma completa de comercio electrónico', 'capacidad': 100, 'unidad': 'un'},
            {'nombre': 'Sistema de Gestión de Inventarios', 'posicion_arancelaria': '8523.49.00', 'descripcion': 'Software de gestión de inventarios', 'capacidad': 150, 'unidad': 'un'},
        ],
        'servicios': [
            {
                'nombre': 'Implementación de ERP',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Servicios de implementación y configuración de sistemas ERP',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, Chile, Uruguay',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'PMP, Agile, Scrum',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Consultoría en Transformación Digital',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Asesoramiento en transformación digital para empresas',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Digital Transformation Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Soporte Técnico',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Servicio de soporte técnico para software',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, Chile',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'mensual',
                'certificaciones_tecnicas': 'ITIL',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Capacitación en Software',
                'tipo_servicio': 'capacitacion',
                'descripcion': 'Cursos de capacitación en uso de software empresarial',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Instructor Certificado',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Migración de Datos',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Servicios de migración de datos entre sistemas',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Data Migration Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
        ],
        'actividades_promocion': [
            {'tipo': 'feria', 'lugar': 'Gartner IT Symposium, Orlando, EEUU', 'anio': '2023', 'observaciones': 'Stand de tecnología'},
            {'tipo': 'feria', 'lugar': 'Argentina IT, Buenos Aires, Argentina', 'anio': '2023', 'observaciones': 'Participación con productos'},
            {'tipo': 'mision', 'lugar': 'São Paulo, Brasil', 'anio': '2023', 'observaciones': 'Misión comercial con empresas'},
            {'tipo': 'mision', 'lugar': 'Santiago, Chile', 'anio': '2022', 'observaciones': 'Expansión en mercado chileno'},
            {'tipo': 'ronda', 'lugar': 'Buenos Aires, Argentina', 'anio': '2023', 'observaciones': 'Ronda de negocios con empresas locales'},
            {'tipo': 'ronda', 'lugar': 'Córdoba, Argentina', 'anio': '2022', 'observaciones': 'Ronda de negocios ProCórdoba'},
        ],
        'departamento_nombre': 'Capital',
        'provincia_nombre': 'Buenos Aires',
    },
    {
        'razon_social': 'AGROTECNOLOGIA Y SERVICIOS S.A.',
        'nombre_fantasia': 'AgroTec',
        'tipo_sociedad': 'Sociedad Anónima',
        'cuit': '30500018354',
        'direccion': 'Ruta Nacional 9 Km 305',
        'codigo_postal': 'B6740',
        'direccion_comercial': 'Ruta Nacional 9 Km 305, General Rodríguez, Buenos Aires',
        'codigo_postal_comercial': 'B6740',
        'telefono': '+542374568000',
        'correo': 'contacto@agrotec.com.ar',
        'sitioweb': 'https://www.agrotec.com.ar',
        'instagram': '@agrotecarg',
        'facebook': 'AgroTecArgentina',
        'linkedin': 'agrotec-argentina',
        'geolocalizacion': '-34.608333,-58.973333',  # General Rodríguez, Buenos Aires
        'descripcion': 'Empresa que desarrolla maquinaria agrícola y ofrece servicios de mantenimiento y consultoría.',
        'observaciones': 'Empresa que combina productos de maquinaria agrícola con servicios de mantenimiento.',
        'exporta': 'Sí',
        'destinoexporta': 'Brasil, Paraguay, Uruguay, Chile, Estados Unidos',
        'tipoexporta': 'Directa',
        'importa': True,
        'certificadopyme': False,
        'certificaciones': 'ISO 9001, ISO 14001',
        'idiomas_trabaja': 'Español, Inglés, Portugués',
        'promo2idiomas': True,
        'participoferianacional': True,
        'feriasnacionales': 'Expoagro 2023, La Rural 2023',
        'participoferiainternacional': True,
        'feriasinternacionales': 'Agritechnica 2023 (Alemania), Expoagro 2023 (Brasil)',
        'contacto_principal_nombre': 'Fernando López',
        'contacto_principal_cargo': 'Director General',
        'contacto_principal_telefono': '+542374568000',
        'contacto_principal_email': 'flopez@agrotec.com.ar',
        'contacto_secundario_nombre': 'Patricia Gómez',
        'contacto_secundario_cargo': 'Gerente de Exportaciones',
        'contacto_secundario_telefono': '+542374568001',
        'contacto_secundario_email': 'pgomez@agrotec.com.ar',
        'productos': [
            {'nombre': 'Sembradora de Precisión', 'posicion_arancelaria': '8432.30.00', 'descripcion': 'Sembradora de precisión con GPS', 'capacidad': 50, 'unidad': 'un'},
            {'nombre': 'Pulverizadora Autopropulsada', 'posicion_arancelaria': '8424.81.00', 'descripcion': 'Pulverizadora para cultivos', 'capacidad': 30, 'unidad': 'un'},
            {'nombre': 'Cosechadora de Granos', 'posicion_arancelaria': '8433.51.00', 'descripcion': 'Cosechadora de granos con tecnología avanzada', 'capacidad': 20, 'unidad': 'un'},
            {'nombre': 'Tractor Agrícola', 'posicion_arancelaria': '8701.90.00', 'descripcion': 'Tractor agrícola de alta potencia', 'capacidad': 40, 'unidad': 'un'},
            {'nombre': 'Sistema de Riego por Goteo', 'posicion_arancelaria': '8424.81.00', 'descripcion': 'Sistema completo de riego por goteo', 'capacidad': 100, 'unidad': 'un'},
        ],
        'servicios': [
            {
                'nombre': 'Mantenimiento de Maquinaria Agrícola',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Servicios de mantenimiento y reparación de maquinaria agrícola',
                'sector_atendido': 'agroindustria',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, Paraguay, Uruguay, Chile',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Técnico en Maquinaria Agrícola',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Consultoría Agrícola',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Asesoramiento en técnicas agrícolas y optimización de cultivos',
                'sector_atendido': 'agroindustria',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, Paraguay, Uruguay',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Ingeniero Agrónomo',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Capacitación en Uso de Maquinaria',
                'tipo_servicio': 'capacitacion',
                'descripcion': 'Cursos de capacitación en uso y mantenimiento de maquinaria agrícola',
                'sector_atendido': 'agroindustria',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Instructor Certificado',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Instalación de Sistemas de Riego',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Servicios de instalación y configuración de sistemas de riego',
                'sector_atendido': 'agroindustria',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, Paraguay, Uruguay',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Técnico en Riego',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Análisis de Suelos y Cultivos',
                'tipo_servicio': 'investigacion_desarrollo',
                'descripcion': 'Servicios de análisis de suelos y recomendaciones de cultivos',
                'sector_atendido': 'agroindustria',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Laboratorio Certificado',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
        ],
        'actividades_promocion': [
            {'tipo': 'feria', 'lugar': 'Agritechnica, Hannover, Alemania', 'anio': '2023', 'observaciones': 'Stand de maquinaria'},
            {'tipo': 'feria', 'lugar': 'Expoagro, São Paulo, Brasil', 'anio': '2023', 'observaciones': 'Participación con productos'},
            {'tipo': 'mision', 'lugar': 'Asunción, Paraguay', 'anio': '2023', 'observaciones': 'Misión comercial con productores'},
            {'tipo': 'mision', 'lugar': 'Montevideo, Uruguay', 'anio': '2022', 'observaciones': 'Expansión en mercado uruguayo'},
            {'tipo': 'ronda', 'lugar': 'Buenos Aires, Argentina', 'anio': '2023', 'observaciones': 'Ronda de negocios con productores'},
            {'tipo': 'ronda', 'lugar': 'Rosario, Argentina', 'anio': '2022', 'observaciones': 'Ronda de negocios ProCórdoba'},
        ],
        'departamento_nombre': 'General Rodríguez',
        'provincia_nombre': 'Buenos Aires',
    },
    {
        'razon_social': 'DISEÑO Y PRODUCCION TEXTIL S.A.',
        'nombre_fantasia': 'TextilPro',
        'tipo_sociedad': 'Sociedad Anónima',
        'cuit': '30500018355',
        'direccion': 'Av. Don Bosco 400',
        'codigo_postal': 'B1878',
        'direccion_comercial': 'Av. Don Bosco 400, Quilmes, Buenos Aires',
        'codigo_postal_comercial': 'B1878',
        'telefono': '+541142346000',
        'correo': 'contacto@textilpro.com.ar',
        'sitioweb': 'https://www.textilpro.com.ar',
        'instagram': '@textilpro',
        'facebook': 'TextilPro',
        'linkedin': 'textilpro-argentina',
        'geolocalizacion': '-34.720556,-58.254167',  # Quilmes, Buenos Aires
        'descripcion': 'Empresa que produce textiles y ofrece servicios de diseño y confección personalizada.',
        'observaciones': 'Empresa que combina producción textil con servicios de diseño y confección.',
        'exporta': 'Sí',
        'destinoexporta': 'Brasil, Chile, Uruguay, Estados Unidos, España',
        'tipoexporta': 'Mixta',
        'importa': True,
        'certificadopyme': True,
        'certificaciones': 'ISO 9001, Oeko-Tex Standard 100',
        'idiomas_trabaja': 'Español, Inglés, Portugués',
        'promo2idiomas': True,
        'participoferianacional': True,
        'feriasnacionales': 'Moda Buenos Aires 2023, Textil Expo 2023',
        'participoferiainternacional': True,
        'feriasinternacionales': 'Première Vision 2023 (Francia), Texworld 2023 (Alemania)',
        'contacto_principal_nombre': 'Diego Herrera',
        'contacto_principal_cargo': 'Director General',
        'contacto_principal_telefono': '+541142346000',
        'contacto_principal_email': 'dherrera@textilpro.com.ar',
        'contacto_secundario_nombre': 'Sofía Martínez',
        'contacto_secundario_cargo': 'Gerente de Diseño',
        'contacto_secundario_telefono': '+541142346001',
        'contacto_secundario_email': 'smartinez@textilpro.com.ar',
        'productos': [
            {'nombre': 'Telas de Algodón', 'posicion_arancelaria': '5208.11.00', 'descripcion': 'Telas de algodón de alta calidad', 'capacidad': 50000, 'unidad': 'm'},
            {'nombre': 'Telas de Poliéster', 'posicion_arancelaria': '5407.61.00', 'descripcion': 'Telas de poliéster para confección', 'capacidad': 40000, 'unidad': 'm'},
            {'nombre': 'Prendas de Vestir', 'posicion_arancelaria': '6109.10.00', 'descripcion': 'Prendas de vestir confeccionadas', 'capacidad': 20000, 'unidad': 'un'},
            {'nombre': 'Textiles para el Hogar', 'posicion_arancelaria': '6302.21.00', 'descripcion': 'Textiles para decoración del hogar', 'capacidad': 15000, 'unidad': 'un'},
            {'nombre': 'Telas Técnicas', 'posicion_arancelaria': '5903.10.00', 'descripcion': 'Telas técnicas para uso industrial', 'capacidad': 10000, 'unidad': 'm'},
        ],
        'servicios': [
            {
                'nombre': 'Diseño de Moda',
                'tipo_servicio': 'diseno_marketing',
                'descripcion': 'Servicios de diseño de moda y colecciones',
                'sector_atendido': 'comercio',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, Chile, Uruguay, Estados Unidos',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Diseñador de Moda Certificado',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Confección Personalizada',
                'tipo_servicio': 'culturales_eventos',
                'descripcion': 'Servicios de confección de prendas personalizadas',
                'sector_atendido': 'comercio',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Confeccionista Certificado',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Consultoría en Textiles',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Asesoramiento en selección y uso de textiles',
                'sector_atendido': 'comercio',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Consultor Textil',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Capacitación en Confección',
                'tipo_servicio': 'capacitacion',
                'descripcion': 'Cursos de capacitación en técnicas de confección',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Instructor Certificado',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Estampado y Serigrafía',
                'tipo_servicio': 'diseno_marketing',
                'descripcion': 'Servicios de estampado y serigrafía sobre textiles',
                'sector_atendido': 'comercio',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Estampador Certificado',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
        ],
        'actividades_promocion': [
            {'tipo': 'feria', 'lugar': 'Première Vision, París, Francia', 'anio': '2023', 'observaciones': 'Stand de textiles'},
            {'tipo': 'feria', 'lugar': 'Texworld, Frankfurt, Alemania', 'anio': '2023', 'observaciones': 'Participación con productos'},
            {'tipo': 'mision', 'lugar': 'São Paulo, Brasil', 'anio': '2023', 'observaciones': 'Misión comercial con diseñadores'},
            {'tipo': 'mision', 'lugar': 'Santiago, Chile', 'anio': '2022', 'observaciones': 'Expansión en mercado chileno'},
            {'tipo': 'ronda', 'lugar': 'Buenos Aires, Argentina', 'anio': '2023', 'observaciones': 'Ronda de negocios con diseñadores'},
            {'tipo': 'ronda', 'lugar': 'Quilmes, Argentina', 'anio': '2022', 'observaciones': 'Ronda de negocios ProCórdoba'},
        ],
        'departamento_nombre': 'Quilmes',
        'provincia_nombre': 'Buenos Aires',
    },
]


class Command(BaseCommand):
    help = 'Carga empresas mixtas con todos los campos completos'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Iniciando carga de empresas mixtas...'))
        
        # Obtener o crear rol de empresa
        rol_empresa, _ = RolUsuario.objects.get_or_create(
            nombre='Empresa',
            defaults={'descripcion': 'Rol para empresas registradas', 'nivel_acceso': 1}
        )
        
        # Obtener tipo de empresa "mixta"
        tipo_empresa = TipoEmpresa.objects.filter(nombre__icontains='mixta').first()
        if not tipo_empresa:
            tipo_empresa = TipoEmpresa.objects.first()
        
        empresas_creadas = 0
        
        with transaction.atomic():
            for empresa_data in EMPRESAS_MIXTAS:
                try:
                    # Obtener departamento
                    departamento = Departamento.objects.filter(
                        nombre__icontains=empresa_data['departamento_nombre']
                    ).first()
                    if not departamento:
                        departamento = Departamento.objects.first()
                    
                    # Obtener municipio y localidad si es posible
                    municipio = None
                    localidad = None
                    if departamento:
                        municipio = Municipio.objects.filter(departamento=departamento).first()
                        if municipio:
                            localidad = Localidad.objects.filter(municipio=municipio).first()
                    
                    # Obtener rubro y subrubro (usar los primeros disponibles)
                    rubro = Rubro.objects.first()
                    subrubro = SubRubro.objects.filter(rubro=rubro).first() if rubro else None
                    
                    # Parsear geolocalización
                    geoloc = empresa_data.get('geolocalizacion', '').split(',')
                    latitud = Decimal(geoloc[0]) if len(geoloc) > 0 and geoloc[0] else None
                    longitud = Decimal(geoloc[1]) if len(geoloc) > 1 and geoloc[1] else None
                    
                    # Crear usuario para la empresa
                    usuario, created = Usuario.objects.get_or_create(
                        email=empresa_data['contacto_principal_email'],
                        defaults={
                            'password': empresa_data['cuit'],
                            'rol': rol_empresa,
                            'nombre': empresa_data['contacto_principal_nombre'].split()[0],
                            'apellido': ' '.join(empresa_data['contacto_principal_nombre'].split()[1:]) if len(empresa_data['contacto_principal_nombre'].split()) > 1 else '',
                            'telefono': empresa_data['contacto_principal_telefono'],
                            'is_active': True,
                        }
                    )
                    if not created:
                        usuario.set_password(empresa_data['cuit'])
                        usuario.save()
                    
                    # Preparar redes sociales como JSON
                    redes_sociales = {}
                    if empresa_data.get('instagram'):
                        redes_sociales['instagram'] = empresa_data['instagram']
                    if empresa_data.get('facebook'):
                        redes_sociales['facebook'] = empresa_data['facebook']
                    if empresa_data.get('linkedin'):
                        redes_sociales['linkedin'] = empresa_data['linkedin']
                    
                    # Crear empresa
                    empresa = Empresa.objects.create(
                        razon_social=empresa_data['razon_social'],
                        nombre_fantasia=empresa_data.get('nombre_fantasia'),
                        tipo_sociedad=empresa_data.get('tipo_sociedad'),
                        cuit_cuil=empresa_data['cuit'],
                        direccion=empresa_data['direccion'],
                        codigo_postal=empresa_data.get('codigo_postal'),
                        direccion_comercial=empresa_data.get('direccion_comercial'),
                        codigo_postal_comercial=empresa_data.get('codigo_postal_comercial'),
                        departamento=departamento,
                        municipio=municipio,
                        localidad=localidad,
                        geolocalizacion=empresa_data.get('geolocalizacion'),
                        latitud=latitud,
                        longitud=longitud,
                        telefono=empresa_data.get('telefono'),
                        correo=empresa_data.get('correo'),
                        sitioweb=empresa_data.get('sitioweb'),
                        redes_sociales=json.dumps(redes_sociales) if redes_sociales else None,
                        descripcion=empresa_data.get('descripcion'),
                        observaciones=empresa_data.get('observaciones'),
                        exporta=empresa_data.get('exporta'),
                        destinoexporta=empresa_data.get('destinoexporta'),
                        tipoexporta=empresa_data.get('tipoexporta'),
                        importa=empresa_data.get('importa', False),
                        certificadopyme=empresa_data.get('certificadopyme', False),
                        certificaciones=empresa_data.get('certificaciones'),
                        idiomas_trabaja=empresa_data.get('idiomas_trabaja'),
                        promo2idiomas=empresa_data.get('promo2idiomas', False),
                        participoferianacional=empresa_data.get('participoferianacional', False),
                        feriasnacionales=empresa_data.get('feriasnacionales'),
                        participoferiainternacional=empresa_data.get('participoferiainternacional', False),
                        feriasinternacionales=empresa_data.get('feriasinternacionales'),
                        contacto_principal_nombre=empresa_data['contacto_principal_nombre'],
                        contacto_principal_cargo=empresa_data['contacto_principal_cargo'],
                        contacto_principal_telefono=empresa_data['contacto_principal_telefono'],
                        contacto_principal_email=empresa_data['contacto_principal_email'],
                        contacto_secundario_nombre=empresa_data.get('contacto_secundario_nombre'),
                        contacto_secundario_cargo=empresa_data.get('contacto_secundario_cargo'),
                        contacto_secundario_telefono=empresa_data.get('contacto_secundario_telefono'),
                        contacto_secundario_email=empresa_data.get('contacto_secundario_email'),
                        id_usuario=usuario,
                        id_rubro=rubro,
                        tipo_empresa=tipo_empresa,
                        tipo_empresa_valor='mixta',
                        actividades_promocion_internacional=empresa_data.get('actividades_promocion', []),
                    )
                    
                    # Crear productos (usando ProductoEmpresaMixta)
                    for producto_data in empresa_data.get('productos', []):
                        producto = ProductoEmpresaMixta.objects.create(
                            empresa=empresa,
                            nombre_producto=producto_data['nombre'],
                            descripcion=producto_data['descripcion'],
                            capacidad_productiva=Decimal(producto_data['capacidad']),
                            unidad_medida=producto_data['unidad'],
                            periodo_capacidad='mensual',
                            es_principal=(producto_data == empresa_data['productos'][0]),
                        )
                        
                        # Crear posición arancelaria (si el producto tiene una)
                        if 'posicion_arancelaria' in producto_data:
                            # Para productos mixtos, necesitamos crear un ProductoEmpresa temporal o usar otra estructura
                            # Por ahora, crearemos la posición arancelaria directamente si es posible
                            # Nota: PosicionArancelaria requiere un ProductoEmpresa, no ProductoEmpresaMixta
                            # Necesitamos verificar si hay un modelo similar para mixtas
                            pass
                    
                    # Crear servicios (usando ServicioEmpresaMixta)
                    for servicio_data in empresa_data.get('servicios', []):
                        ServicioEmpresaMixta.objects.create(
                            empresa=empresa,
                            nombre_servicio=servicio_data['nombre'],
                            descripcion=servicio_data['descripcion'],
                            tipo_servicio=servicio_data['tipo_servicio'],
                            sector_atendido=servicio_data['sector_atendido'],
                            alcance_servicio=servicio_data['alcance_servicio'],
                            paises_trabaja=servicio_data.get('paises_trabaja'),
                            exporta_servicios=servicio_data.get('exporta_servicios', False),
                            interes_exportar_servicios=servicio_data.get('interes_exportar_servicios', False),
                            idiomas_trabajo=servicio_data.get('idiomas_trabajo'),
                            forma_contratacion=servicio_data['forma_contratacion'],
                            certificaciones_tecnicas=servicio_data.get('certificaciones_tecnicas'),
                            tiene_equipo_tecnico=servicio_data.get('tiene_equipo_tecnico', False),
                            equipo_tecnico_formacion=servicio_data.get('equipo_tecnico_formacion', False),
                            es_principal=(servicio_data == empresa_data['servicios'][0]),
                        )
                    
                    empresas_creadas += 1
                    self.stdout.write(
                        self.style.SUCCESS(f'✓ Empresa creada: {empresa.razon_social} (ID: {empresa.id})')
                    )
                    
                except Exception as e:
                    self.stdout.write(
                        self.style.ERROR(f'✗ Error al crear empresa {empresa_data.get("razon_social", "desconocida")}: {str(e)}')
                    )
                    import traceback
                    traceback.print_exc()
        
        self.stdout.write(
            self.style.SUCCESS(f'\n✓ Proceso completado. Empresas creadas: {empresas_creadas}/{len(EMPRESAS_MIXTAS)}')
        )

