"""
Management command para cargar empresas de servicios con todos los campos completos
"""
from django.core.management.base import BaseCommand
from django.db import transaction
from apps.empresas.models import (
    Empresa, TipoEmpresa, Rubro, SubRubro, ServicioEmpresa
)
from apps.core.models import Usuario, RolUsuario
from apps.geografia.models import Departamento, Municipio, Localidad
import random
from decimal import Decimal
import json

# Datos de empresas reales argentinas que ofrecen servicios
EMPRESAS_SERVICIOS = [
    {
        'razon_social': 'GLOBANT S.A.',
        'nombre_fantasia': 'Globant',
        'tipo_sociedad': 'Sociedad Anónima',
        'cuit': '30500018346',
        'direccion': 'Av. Corrientes 222, Piso 8',
        'codigo_postal': 'C1043',
        'direccion_comercial': 'Av. Corrientes 222, CABA',
        'codigo_postal_comercial': 'C1043',
        'telefono': '+541143212500',
        'correo': 'contacto@globant.com',
        'sitioweb': 'https://www.globant.com',
        'instagram': '@globant',
        'facebook': 'Globant',
        'linkedin': 'globant',
        'geolocalizacion': '-34.603722,-58.381592',  # Buenos Aires
        'descripcion': 'Empresa líder en servicios de tecnología de la información, desarrollo de software y consultoría digital.',
        'observaciones': 'Empresa multinacional con presencia en más de 20 países, especializada en transformación digital.',
        'exporta': 'Sí',
        'destinoexporta': 'Estados Unidos, Reino Unido, España, México, Colombia, Brasil, Chile',
        'tipoexporta': 'Directa',
        'importa': False,
        'certificadopyme': False,
        'certificaciones': 'ISO 9001, ISO 27001, CMMI Level 5, AWS Partner, Google Cloud Partner',
        'idiomas_trabaja': 'Español, Inglés, Portugués, Francés',
        'promo2idiomas': True,
        'participoferianacional': True,
        'feriasnacionales': 'Expo Tecnología 2023, Argentina IT 2023',
        'participoferiainternacional': True,
        'feriasinternacionales': 'Web Summit 2023 (Portugal), SXSW 2023 (EEUU), Mobile World Congress 2023 (España)',
        'contacto_principal_nombre': 'Martín Migoya',
        'contacto_principal_cargo': 'CEO',
        'contacto_principal_telefono': '+541143212500',
        'contacto_principal_email': 'mmigoya@globant.com',
        'contacto_secundario_nombre': 'Patricia Pomies',
        'contacto_secundario_cargo': 'Chief Operating Officer',
        'contacto_secundario_telefono': '+541143212501',
        'contacto_secundario_email': 'ppomies@globant.com',
        'servicios': [
            {
                'nombre': 'Desarrollo de Software a Medida',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Desarrollo de aplicaciones web, móviles y de escritorio personalizadas',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Reino Unido, España, México, Colombia, Brasil, Chile, Argentina',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'AWS Certified, Google Cloud Certified, Microsoft Azure Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Consultoría en Transformación Digital',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Asesoramiento estratégico para la transformación digital de empresas',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Reino Unido, España, México, Colombia, Brasil',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Agile, Scrum, PMP',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Diseño UX/UI',
                'tipo_servicio': 'diseno_marketing',
                'descripcion': 'Diseño de interfaces de usuario y experiencias de usuario',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Reino Unido, España, México, Brasil',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Adobe Certified, Figma Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Cloud Computing y DevOps',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Servicios de infraestructura en la nube y automatización de procesos',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Reino Unido, España, México, Brasil',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'mensual',
                'certificaciones_tecnicas': 'AWS Certified, Kubernetes Certified, Docker Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Inteligencia Artificial y Machine Learning',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Desarrollo de soluciones de IA y ML para empresas',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Reino Unido, España, México, Brasil',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'TensorFlow Certified, PyTorch Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
        ],
        'actividades_promocion': [
            {'tipo': 'feria', 'lugar': 'Web Summit, Lisboa, Portugal', 'anio': '2023', 'observaciones': 'Stand principal, 300m²'},
            {'tipo': 'feria', 'lugar': 'SXSW, Austin, EEUU', 'anio': '2023', 'observaciones': 'Participación con productos de IA'},
            {'tipo': 'mision', 'lugar': 'San Francisco, EEUU', 'anio': '2023', 'observaciones': 'Misión comercial con empresas tecnológicas'},
            {'tipo': 'mision', 'lugar': 'Londres, Reino Unido', 'anio': '2022', 'observaciones': 'Expansión en mercado europeo'},
            {'tipo': 'ronda', 'lugar': 'Buenos Aires, Argentina', 'anio': '2023', 'observaciones': 'Ronda de negocios con empresas locales'},
            {'tipo': 'ronda', 'lugar': 'Córdoba, Argentina', 'anio': '2022', 'observaciones': 'Ronda de negocios ProCórdoba'},
        ],
        'departamento_nombre': 'Capital',
        'provincia_nombre': 'Buenos Aires',
    },
    {
        'razon_social': 'MERCADOLIBRE S.A.',
        'nombre_fantasia': 'MercadoLibre',
        'tipo_sociedad': 'Sociedad Anónima',
        'cuit': '30500018347',
        'direccion': 'Ariosto 2000',
        'codigo_postal': 'C1414',
        'direccion_comercial': 'Ariosto 2000, CABA',
        'codigo_postal_comercial': 'C1414',
        'telefono': '+541143212600',
        'correo': 'contacto@mercadolibre.com',
        'sitioweb': 'https://www.mercadolibre.com.ar',
        'instagram': '@mercadolibre',
        'facebook': 'MercadoLibre',
        'linkedin': 'mercadolibre',
        'geolocalizacion': '-34.571389,-58.437778',  # Buenos Aires
        'descripcion': 'Plataforma de comercio electrónico líder en Latinoamérica, ofreciendo servicios de marketplace, pagos y logística.',
        'observaciones': 'Empresa con presencia en 18 países de Latinoamérica, líder en e-commerce y fintech.',
        'exporta': 'Sí',
        'destinoexporta': 'Brasil, México, Colombia, Chile, Uruguay, Perú, Ecuador, Venezuela',
        'tipoexporta': 'Directa',
        'importa': False,
        'certificadopyme': False,
        'certificaciones': 'PCI DSS, ISO 27001, SOC 2',
        'idiomas_trabaja': 'Español, Inglés, Portugués',
        'promo2idiomas': True,
        'participoferianacional': True,
        'feriasnacionales': 'E-commerce Day 2023, Digital Commerce Summit 2023',
        'participoferiainternacional': True,
        'feriasinternacionales': 'eCommerce Expo 2023 (Brasil), Retail Innovation Summit 2023 (México)',
        'contacto_principal_nombre': 'Marcos Galperin',
        'contacto_principal_cargo': 'CEO y Fundador',
        'contacto_principal_telefono': '+541143212600',
        'contacto_principal_email': 'mgalperin@mercadolibre.com',
        'contacto_secundario_nombre': 'Pedro Arnt',
        'contacto_secundario_cargo': 'Chief Financial Officer',
        'contacto_secundario_telefono': '+541143212601',
        'contacto_secundario_email': 'parnt@mercadolibre.com',
        'servicios': [
            {
                'nombre': 'Plataforma de Marketplace',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Plataforma de comercio electrónico para compradores y vendedores',
                'sector_atendido': 'comercio',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, México, Colombia, Chile, Uruguay, Perú, Ecuador',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'mensual',
                'certificaciones_tecnicas': 'PCI DSS, ISO 27001',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Mercado Pago - Soluciones de Pago',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Plataforma de pagos online y offline para empresas y usuarios',
                'sector_atendido': 'comercio',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, México, Colombia, Chile, Uruguay',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'mensual',
                'certificaciones_tecnicas': 'PCI DSS, SOC 2',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Mercado Envíos - Logística',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Servicios de logística y envío para e-commerce',
                'sector_atendido': 'comercio',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, México, Colombia, Chile',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'mensual',
                'certificaciones_tecnicas': 'ISO 9001',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Publicidad Digital',
                'tipo_servicio': 'diseno_marketing',
                'descripcion': 'Servicios de publicidad y marketing digital para vendedores',
                'sector_atendido': 'comercio',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, México, Colombia, Chile',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'mensual',
                'certificaciones_tecnicas': 'Google Ads Certified, Facebook Blueprint',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Consultoría E-commerce',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Asesoramiento para empresas que quieren vender online',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'E-commerce Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
        ],
        'actividades_promocion': [
            {'tipo': 'feria', 'lugar': 'eCommerce Expo, São Paulo, Brasil', 'anio': '2023', 'observaciones': 'Stand principal'},
            {'tipo': 'feria', 'lugar': 'Retail Innovation Summit, Ciudad de México, México', 'anio': '2023', 'observaciones': 'Participación con nuevas tecnologías'},
            {'tipo': 'mision', 'lugar': 'Bogotá, Colombia', 'anio': '2023', 'observaciones': 'Misión comercial con retailers'},
            {'tipo': 'mision', 'lugar': 'Santiago, Chile', 'anio': '2022', 'observaciones': 'Expansión en mercado chileno'},
            {'tipo': 'ronda', 'lugar': 'Buenos Aires, Argentina', 'anio': '2023', 'observaciones': 'Ronda de negocios con empresas locales'},
            {'tipo': 'ronda', 'lugar': 'Rosario, Argentina', 'anio': '2022', 'observaciones': 'Ronda de negocios ProCórdoba'},
        ],
        'departamento_nombre': 'Capital',
        'provincia_nombre': 'Buenos Aires',
    },
    {
        'razon_social': 'DESPEGAR.COM S.A.',
        'nombre_fantasia': 'Despegar',
        'tipo_sociedad': 'Sociedad Anónima',
        'cuit': '30500018348',
        'direccion': 'Juana Manso 1069',
        'codigo_postal': 'C1107',
        'direccion_comercial': 'Juana Manso 1069, CABA',
        'codigo_postal_comercial': 'C1107',
        'telefono': '+541143212700',
        'correo': 'contacto@despegar.com',
        'sitioweb': 'https://www.despegar.com.ar',
        'instagram': '@despegar',
        'facebook': 'Despegar',
        'linkedin': 'despegar',
        'geolocalizacion': '-34.603722,-58.381592',  # Buenos Aires
        'descripcion': 'Agencia de viajes online líder en Latinoamérica, especializada en turismo receptivo y servicios de viaje.',
        'observaciones': 'Empresa con presencia en 20 países, líder en turismo online en la región.',
        'exporta': 'Sí',
        'destinoexporta': 'Brasil, México, Colombia, Chile, Uruguay, Perú, Ecuador, Estados Unidos',
        'tipoexporta': 'Directa',
        'importa': False,
        'certificadopyme': False,
        'certificaciones': 'IATA, ISO 9001',
        'idiomas_trabaja': 'Español, Inglés, Portugués',
        'promo2idiomas': True,
        'participoferianacional': True,
        'feriasnacionales': 'FIT 2023 (Feria Internacional de Turismo), Travel Expo 2023',
        'participoferiainternacional': True,
        'feriasinternacionales': 'WTM 2023 (World Travel Market, Londres), ITB 2023 (Berlín)',
        'contacto_principal_nombre': 'Roberto Souviron',
        'contacto_principal_cargo': 'CEO',
        'contacto_principal_telefono': '+541143212700',
        'contacto_principal_email': 'rsouviron@despegar.com',
        'contacto_secundario_nombre': 'Alejandro Tamer',
        'contacto_secundario_cargo': 'Chief Operating Officer',
        'contacto_secundario_telefono': '+541143212701',
        'contacto_secundario_email': 'atamer@despegar.com',
        'servicios': [
            {
                'nombre': 'Turismo Receptivo',
                'tipo_servicio': 'turismo_receptivo',
                'descripcion': 'Servicios de turismo receptivo para visitantes internacionales',
                'sector_atendido': 'turismo',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, México, Colombia, Chile, Uruguay, Perú',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués, Francés, Alemán',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'IATA',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Reservas de Hoteles',
                'tipo_servicio': 'turismo_receptivo',
                'descripcion': 'Plataforma de reservas de hoteles online',
                'sector_atendido': 'turismo',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, México, Colombia, Chile, Uruguay',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'mensual',
                'certificaciones_tecnicas': 'IATA',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Vuelos y Paquetes Turísticos',
                'tipo_servicio': 'turismo_receptivo',
                'descripcion': 'Venta de vuelos y paquetes turísticos completos',
                'sector_atendido': 'turismo',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, México, Colombia, Chile, Uruguay',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'IATA',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Alquiler de Autos',
                'tipo_servicio': 'turismo_receptivo',
                'descripcion': 'Servicio de alquiler de autos para turistas',
                'sector_atendido': 'turismo',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, México, Colombia, Chile',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'IATA',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Actividades y Excursiones',
                'tipo_servicio': 'turismo_receptivo',
                'descripcion': 'Venta de actividades turísticas y excursiones',
                'sector_atendido': 'turismo',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, México, Colombia, Chile',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'IATA',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
        ],
        'actividades_promocion': [
            {'tipo': 'feria', 'lugar': 'WTM, Londres, Reino Unido', 'anio': '2023', 'observaciones': 'Stand principal'},
            {'tipo': 'feria', 'lugar': 'ITB, Berlín, Alemania', 'anio': '2023', 'observaciones': 'Participación con productos de turismo'},
            {'tipo': 'mision', 'lugar': 'Madrid, España', 'anio': '2023', 'observaciones': 'Misión comercial con agencias de viaje'},
            {'tipo': 'mision', 'lugar': 'São Paulo, Brasil', 'anio': '2022', 'observaciones': 'Expansión en mercado brasileño'},
            {'tipo': 'ronda', 'lugar': 'Buenos Aires, Argentina', 'anio': '2023', 'observaciones': 'Ronda de negocios con hoteles'},
            {'tipo': 'ronda', 'lugar': 'Bariloche, Argentina', 'anio': '2022', 'observaciones': 'Ronda de negocios ProCórdoba'},
        ],
        'departamento_nombre': 'Capital',
        'provincia_nombre': 'Buenos Aires',
    },
    {
        'razon_social': 'ACCENTURE S.A.',
        'nombre_fantasia': 'Accenture Argentina',
        'tipo_sociedad': 'Sociedad Anónima',
        'cuit': '30500018349',
        'direccion': 'Av. Leandro N. Alem 1050',
        'codigo_postal': 'C1001',
        'direccion_comercial': 'Av. Leandro N. Alem 1050, CABA',
        'codigo_postal_comercial': 'C1001',
        'telefono': '+541143212800',
        'correo': 'contacto@accenture.com',
        'sitioweb': 'https://www.accenture.com/ar-es',
        'instagram': '@accenture',
        'facebook': 'Accenture',
        'linkedin': 'accenture',
        'geolocalizacion': '-34.603722,-58.381592',  # Buenos Aires
        'descripcion': 'Empresa multinacional de consultoría, servicios tecnológicos y outsourcing.',
        'observaciones': 'Empresa líder mundial en servicios de consultoría y tecnología.',
        'exporta': 'Sí',
        'destinoexporta': 'Estados Unidos, Reino Unido, España, Brasil, México, Colombia, Chile',
        'tipoexporta': 'Directa',
        'importa': False,
        'certificadopyme': False,
        'certificaciones': 'ISO 9001, ISO 27001, CMMI Level 5, PMP',
        'idiomas_trabaja': 'Español, Inglés, Portugués, Francés',
        'promo2idiomas': True,
        'participoferianacional': True,
        'feriasnacionales': 'Argentina IT 2023, Digital Transformation Summit 2023',
        'participoferiainternacional': True,
        'feriasinternacionales': 'Gartner IT Symposium 2023 (EEUU), CeBIT 2023 (Alemania)',
        'contacto_principal_nombre': 'Gabriel Rozman',
        'contacto_principal_cargo': 'Country Managing Director',
        'contacto_principal_telefono': '+541143212800',
        'contacto_principal_email': 'grozman@accenture.com',
        'contacto_secundario_nombre': 'María Laura Ramos',
        'contacto_secundario_cargo': 'Managing Director - Technology',
        'contacto_secundario_telefono': '+541143212801',
        'contacto_secundario_email': 'mlramos@accenture.com',
        'servicios': [
            {
                'nombre': 'Consultoría Estratégica',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Consultoría estratégica para transformación de negocios',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Reino Unido, España, Brasil, México, Colombia',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués, Francés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'PMP, Agile, Scrum',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Servicios de Tecnología',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Desarrollo e implementación de soluciones tecnológicas',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Reino Unido, España, Brasil, México',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'CMMI Level 5, AWS Certified, Azure Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Outsourcing de Procesos de Negocio',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Externalización de procesos de negocio (BPO)',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Reino Unido, España, Brasil',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'mensual',
                'certificaciones_tecnicas': 'ISO 9001, ISO 27001',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Servicios de Cloud',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Migración y gestión de servicios en la nube',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Reino Unido, España, Brasil',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'AWS Certified, Azure Certified, Google Cloud Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Seguridad Cibernética',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Servicios de seguridad y protección de datos',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Estados Unidos, Reino Unido, España, Brasil',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'ISO 27001, CISSP, CEH',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
        ],
        'actividades_promocion': [
            {'tipo': 'feria', 'lugar': 'Gartner IT Symposium, Orlando, EEUU', 'anio': '2023', 'observaciones': 'Stand principal'},
            {'tipo': 'feria', 'lugar': 'CeBIT, Hannover, Alemania', 'anio': '2023', 'observaciones': 'Participación con soluciones de IA'},
            {'tipo': 'mision', 'lugar': 'Nueva York, EEUU', 'anio': '2023', 'observaciones': 'Misión comercial con empresas Fortune 500'},
            {'tipo': 'mision', 'lugar': 'Londres, Reino Unido', 'anio': '2022', 'observaciones': 'Expansión en mercado europeo'},
            {'tipo': 'ronda', 'lugar': 'Buenos Aires, Argentina', 'anio': '2023', 'observaciones': 'Ronda de negocios con empresas locales'},
            {'tipo': 'ronda', 'lugar': 'Córdoba, Argentina', 'anio': '2022', 'observaciones': 'Ronda de negocios ProCórdoba'},
        ],
        'departamento_nombre': 'Capital',
        'provincia_nombre': 'Buenos Aires',
    },
    {
        'razon_social': 'BELENUS S.A.',
        'nombre_fantasia': 'Belenus',
        'tipo_sociedad': 'Sociedad Anónima',
        'cuit': '30500018350',
        'direccion': 'Av. Santa Fe 2727',
        'codigo_postal': 'C1425',
        'direccion_comercial': 'Av. Santa Fe 2727, CABA',
        'codigo_postal_comercial': 'C1425',
        'telefono': '+541143212900',
        'correo': 'contacto@belenus.com.ar',
        'sitioweb': 'https://www.belenus.com.ar',
        'instagram': '@belenusarg',
        'facebook': 'BelenusArgentina',
        'linkedin': 'belenus-argentina',
        'geolocalizacion': '-34.571389,-58.437778',  # Buenos Aires
        'descripcion': 'Empresa de servicios de diseño gráfico, branding y marketing digital.',
        'observaciones': 'Empresa especializada en diseño y comunicación visual para empresas.',
        'exporta': 'Sí',
        'destinoexporta': 'Brasil, Chile, Uruguay, Estados Unidos, España',
        'tipoexporta': 'Mixta',
        'importa': False,
        'certificadopyme': True,
        'certificaciones': 'Adobe Certified, Google Ads Certified',
        'idiomas_trabaja': 'Español, Inglés, Portugués',
        'promo2idiomas': True,
        'participoferianacional': True,
        'feriasnacionales': 'Diseño BA 2023, Marketing Digital Summit 2023',
        'participoferiainternacional': True,
        'feriasinternacionales': 'Design Week 2023 (Brasil), Creative Summit 2023 (España)',
        'contacto_principal_nombre': 'Luciana Fernández',
        'contacto_principal_cargo': 'Directora Creativa',
        'contacto_principal_telefono': '+541143212900',
        'contacto_principal_email': 'lfernandez@belenus.com.ar',
        'contacto_secundario_nombre': 'Gonzalo Martínez',
        'contacto_secundario_cargo': 'Gerente de Marketing',
        'contacto_secundario_telefono': '+541143212901',
        'contacto_secundario_email': 'gmartinez@belenus.com.ar',
        'servicios': [
            {
                'nombre': 'Diseño Gráfico y Branding',
                'tipo_servicio': 'diseno_marketing',
                'descripcion': 'Diseño de identidad visual y branding para empresas',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, Chile, Uruguay, Estados Unidos',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Adobe Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Marketing Digital',
                'tipo_servicio': 'diseno_marketing',
                'descripcion': 'Estrategias de marketing digital y redes sociales',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'internacional',
                'paises_trabaja': 'Argentina, Brasil, Chile, Uruguay',
                'exporta_servicios': True,
                'interes_exportar_servicios': False,
                'idiomas_trabajo': 'Español, Inglés, Portugués',
                'forma_contratacion': 'mensual',
                'certificaciones_tecnicas': 'Google Ads Certified, Facebook Blueprint',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Desarrollo Web',
                'tipo_servicio': 'tecnologias',
                'descripcion': 'Desarrollo de sitios web y aplicaciones web',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'WordPress Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Fotografía y Video',
                'tipo_servicio': 'culturales_eventos',
                'descripcion': 'Servicios de fotografía y video corporativo',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Adobe Certified',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
            {
                'nombre': 'Consultoría en Comunicación',
                'tipo_servicio': 'consultoria',
                'descripcion': 'Asesoramiento en estrategias de comunicación',
                'sector_atendido': 'pymes',
                'alcance_servicio': 'nacional',
                'paises_trabaja': 'Argentina',
                'exporta_servicios': False,
                'interes_exportar_servicios': True,
                'idiomas_trabajo': 'Español, Inglés',
                'forma_contratacion': 'proyecto',
                'certificaciones_tecnicas': 'Comunicación Corporativa',
                'tiene_equipo_tecnico': True,
                'equipo_tecnico_formacion': False,
            },
        ],
        'actividades_promocion': [
            {'tipo': 'feria', 'lugar': 'Design Week, São Paulo, Brasil', 'anio': '2023', 'observaciones': 'Stand de diseño'},
            {'tipo': 'feria', 'lugar': 'Creative Summit, Barcelona, España', 'anio': '2023', 'observaciones': 'Participación con portfolio'},
            {'tipo': 'mision', 'lugar': 'Santiago, Chile', 'anio': '2023', 'observaciones': 'Misión comercial con agencias'},
            {'tipo': 'mision', 'lugar': 'Montevideo, Uruguay', 'anio': '2022', 'observaciones': 'Expansión en mercado uruguayo'},
            {'tipo': 'ronda', 'lugar': 'Buenos Aires, Argentina', 'anio': '2023', 'observaciones': 'Ronda de negocios con empresas'},
            {'tipo': 'ronda', 'lugar': 'Córdoba, Argentina', 'anio': '2022', 'observaciones': 'Ronda de negocios ProCórdoba'},
        ],
        'departamento_nombre': 'Capital',
        'provincia_nombre': 'Buenos Aires',
    },
]


class Command(BaseCommand):
    help = 'Carga empresas de servicios con todos los campos completos'

    def handle(self, *args, **options):
        self.stdout.write(self.style.SUCCESS('Iniciando carga de empresas de servicios...'))
        
        # Obtener o crear rol de empresa
        rol_empresa, _ = RolUsuario.objects.get_or_create(
            nombre='Empresa',
            defaults={'descripcion': 'Rol para empresas registradas', 'nivel_acceso': 1}
        )
        
        # Obtener tipo de empresa "servicio"
        tipo_empresa = TipoEmpresa.objects.filter(nombre__icontains='servicio').first()
        if not tipo_empresa:
            tipo_empresa = TipoEmpresa.objects.first()
        
        empresas_creadas = 0
        
        with transaction.atomic():
            for empresa_data in EMPRESAS_SERVICIOS:
                try:
                    # Obtener departamento
                    departamento = Departamento.objects.filter(
                        nombre__icontains=empresa_data['departamento_nombre']
                    ).first()
                    if not departamento:
                        departamento = Departamento.objects.first()
                    
                    # Obtener municipio y localidad si es posible
                    municipio = None
                    localidad = None
                    if departamento:
                        municipio = Municipio.objects.filter(departamento=departamento).first()
                        if municipio:
                            localidad = Localidad.objects.filter(municipio=municipio).first()
                    
                    # Obtener rubro y subrubro (usar los primeros disponibles)
                    rubro = Rubro.objects.first()
                    subrubro = SubRubro.objects.filter(rubro=rubro).first() if rubro else None
                    
                    # Parsear geolocalización
                    geoloc = empresa_data.get('geolocalizacion', '').split(',')
                    latitud = Decimal(geoloc[0]) if len(geoloc) > 0 and geoloc[0] else None
                    longitud = Decimal(geoloc[1]) if len(geoloc) > 1 and geoloc[1] else None
                    
                    # Crear usuario para la empresa
                    usuario, created = Usuario.objects.get_or_create(
                        email=empresa_data['contacto_principal_email'],
                        defaults={
                            'password': empresa_data['cuit'],
                            'rol': rol_empresa,
                            'nombre': empresa_data['contacto_principal_nombre'].split()[0],
                            'apellido': ' '.join(empresa_data['contacto_principal_nombre'].split()[1:]) if len(empresa_data['contacto_principal_nombre'].split()) > 1 else '',
                            'telefono': empresa_data['contacto_principal_telefono'],
                            'is_active': True,
                        }
                    )
                    if not created:
                        usuario.set_password(empresa_data['cuit'])
                        usuario.save()
                    
                    # Preparar redes sociales como JSON
                    redes_sociales = {}
                    if empresa_data.get('instagram'):
                        redes_sociales['instagram'] = empresa_data['instagram']
                    if empresa_data.get('facebook'):
                        redes_sociales['facebook'] = empresa_data['facebook']
                    if empresa_data.get('linkedin'):
                        redes_sociales['linkedin'] = empresa_data['linkedin']
                    
                    # Crear empresa
                    empresa = Empresa.objects.create(
                        razon_social=empresa_data['razon_social'],
                        nombre_fantasia=empresa_data.get('nombre_fantasia'),
                        tipo_sociedad=empresa_data.get('tipo_sociedad'),
                        cuit_cuil=empresa_data['cuit'],
                        direccion=empresa_data['direccion'],
                        codigo_postal=empresa_data.get('codigo_postal'),
                        direccion_comercial=empresa_data.get('direccion_comercial'),
                        codigo_postal_comercial=empresa_data.get('codigo_postal_comercial'),
                        departamento=departamento,
                        municipio=municipio,
                        localidad=localidad,
                        geolocalizacion=empresa_data.get('geolocalizacion'),
                        latitud=latitud,
                        longitud=longitud,
                        telefono=empresa_data.get('telefono'),
                        correo=empresa_data.get('correo'),
                        sitioweb=empresa_data.get('sitioweb'),
                        redes_sociales=json.dumps(redes_sociales) if redes_sociales else None,
                        descripcion=empresa_data.get('descripcion'),
                        observaciones=empresa_data.get('observaciones'),
                        exporta=empresa_data.get('exporta'),
                        destinoexporta=empresa_data.get('destinoexporta'),
                        tipoexporta=empresa_data.get('tipoexporta'),
                        importa=empresa_data.get('importa', False),
                        certificadopyme=empresa_data.get('certificadopyme', False),
                        certificaciones=empresa_data.get('certificaciones'),
                        idiomas_trabaja=empresa_data.get('idiomas_trabaja'),
                        promo2idiomas=empresa_data.get('promo2idiomas', False),
                        participoferianacional=empresa_data.get('participoferianacional', False),
                        feriasnacionales=empresa_data.get('feriasnacionales'),
                        participoferiainternacional=empresa_data.get('participoferiainternacional', False),
                        feriasinternacionales=empresa_data.get('feriasinternacionales'),
                        contacto_principal_nombre=empresa_data['contacto_principal_nombre'],
                        contacto_principal_cargo=empresa_data['contacto_principal_cargo'],
                        contacto_principal_telefono=empresa_data['contacto_principal_telefono'],
                        contacto_principal_email=empresa_data['contacto_principal_email'],
                        contacto_secundario_nombre=empresa_data.get('contacto_secundario_nombre'),
                        contacto_secundario_cargo=empresa_data.get('contacto_secundario_cargo'),
                        contacto_secundario_telefono=empresa_data.get('contacto_secundario_telefono'),
                        contacto_secundario_email=empresa_data.get('contacto_secundario_email'),
                        id_usuario=usuario,
                        id_rubro=rubro,
                        tipo_empresa=tipo_empresa,
                        tipo_empresa_valor='servicio',
                        actividades_promocion_internacional=empresa_data.get('actividades_promocion', []),
                    )
                    
                    # Crear servicios
                    for servicio_data in empresa_data.get('servicios', []):
                        ServicioEmpresa.objects.create(
                            empresa=empresa,
                            nombre_servicio=servicio_data['nombre'],
                            descripcion=servicio_data['descripcion'],
                            tipo_servicio=servicio_data['tipo_servicio'],
                            sector_atendido=servicio_data['sector_atendido'],
                            alcance_servicio=servicio_data['alcance_servicio'],
                            paises_trabaja=servicio_data.get('paises_trabaja'),
                            exporta_servicios=servicio_data.get('exporta_servicios', False),
                            interes_exportar_servicios=servicio_data.get('interes_exportar_servicios', False),
                            idiomas_trabajo=servicio_data.get('idiomas_trabajo'),
                            forma_contratacion=servicio_data['forma_contratacion'],
                            certificaciones_tecnicas=servicio_data.get('certificaciones_tecnicas'),
                            tiene_equipo_tecnico=servicio_data.get('tiene_equipo_tecnico', False),
                            equipo_tecnico_formacion=servicio_data.get('equipo_tecnico_formacion', False),
                            es_principal=(servicio_data == empresa_data['servicios'][0]),
                        )
                    
                    empresas_creadas += 1
                    self.stdout.write(
                        self.style.SUCCESS(f'✓ Empresa creada: {empresa.razon_social} (ID: {empresa.id})')
                    )
                    
                except Exception as e:
                    self.stdout.write(
                        self.style.ERROR(f'✗ Error al crear empresa {empresa_data.get("razon_social", "desconocida")}: {str(e)}')
                    )
                    import traceback
                    traceback.print_exc()
        
        self.stdout.write(
            self.style.SUCCESS(f'\n✓ Proceso completado. Empresas creadas: {empresas_creadas}/{len(EMPRESAS_SERVICIOS)}')
        )

