# Generated by Django 5.2.1 on 2025-10-25 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorialog',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la acción (puede ser NULL para acciones del sistema)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='auditoriacambios',
            name='auditoria_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_detallados', to='auditoria.auditorialog', verbose_name='Registro de Auditoría'),
        ),
        migrations.AddField(
            model_name='auditoriaarchivos',
            name='auditoria_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_afectados', to='auditoria.auditorialog', verbose_name='Registro de Auditoría'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['timestamp'], name='auditoria_l_timesta_8fbe49_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['usuario'], name='auditoria_l_usuario_57b6f3_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['accion'], name='auditoria_l_accion_868eae_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['modelo_afectado'], name='auditoria_l_modelo__87c855_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['categoria'], name='auditoria_l_categor_f5e0e8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditorialog',
            index=models.Index(fields=['nivel_criticidad'], name='auditoria_l_nivel_c_a7bc2b_idx'),
        ),
    ]
