# Generated by Django 5.2.1 on 2025-10-25 01:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dpto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coddpto', models.CharField(max_length=10, unique=True, verbose_name='Código Departamento')),
                ('nomdpto', models.CharField(max_length=100, verbose_name='Nombre del Departamento')),
                ('codprov', models.CharField(max_length=10, verbose_name='Código Provincia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'dpto',
                'ordering': ['nomdpto'],
            },
        ),
        migrations.CreateModel(
            name='RolUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Rol')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('puede_crear_empresas', models.BooleanField(default=False, verbose_name='Puede Crear Empresas')),
                ('puede_editar_empresas', models.BooleanField(default=False, verbose_name='Puede Editar Empresas')),
                ('puede_eliminar_empresas', models.BooleanField(default=False, verbose_name='Puede Eliminar Empresas')),
                ('puede_ver_auditoria', models.BooleanField(default=False, verbose_name='Puede Ver Auditoría')),
                ('puede_exportar_datos', models.BooleanField(default=True, verbose_name='Puede Exportar Datos')),
                ('puede_importar_datos', models.BooleanField(default=False, verbose_name='Puede Importar Datos')),
                ('puede_gestionar_usuarios', models.BooleanField(default=False, verbose_name='Puede Gestionar Usuarios')),
                ('puede_acceder_admin', models.BooleanField(default=False, verbose_name='Puede Acceder al Admin')),
                ('nivel_acceso', models.IntegerField(choices=[(1, 'Consulta'), (2, 'Analista'), (3, 'Administrador')], default=1, verbose_name='Nivel de Acceso')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuario',
                'db_table': 'rol_usuario',
                'ordering': ['nivel_acceso', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codmun', models.CharField(max_length=10, unique=True, verbose_name='Código Municipio')),
                ('nommun', models.CharField(max_length=100, verbose_name='Nombre del Municipio')),
                ('coddpto', models.CharField(max_length=10, verbose_name='Código Departamento')),
                ('codprov', models.CharField(max_length=10, verbose_name='Código Provincia')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('dpto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='core.dpto')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipio',
                'ordering': ['nommun'],
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codloc', models.CharField(max_length=20, unique=True, verbose_name='Código Localidad')),
                ('codlocsv', models.CharField(max_length=10, verbose_name='Código Localidad SV')),
                ('nomloc', models.CharField(max_length=100, verbose_name='Nombre de la Localidad')),
                ('codmun', models.CharField(max_length=10, verbose_name='Código Municipio')),
                ('coddpto', models.CharField(max_length=10, verbose_name='Código Departamento')),
                ('codprov', models.CharField(max_length=10, verbose_name='Código Provincia')),
                ('codpais', models.CharField(max_length=10, verbose_name='Código País')),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('codpos', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='core.municipio')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'localidades',
                'ordering': ['nomloc'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Es Staff')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Es Superusuario')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Avatar')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, null=True, verbose_name='Género')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('PAS', 'Pasaporte'), ('LE', 'Libreta de Enrolamiento')], default='DNI', max_length=10, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Documento')),
                ('fecha_ultimo_acceso', models.DateTimeField(blank=True, null=True, verbose_name='Último Acceso')),
                ('intentos_login_fallidos', models.PositiveIntegerField(default=0, verbose_name='Intentos de Login Fallidos')),
                ('bloqueado_hasta', models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado Hasta')),
                ('departamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('rol', models.ForeignKey(blank=True, help_text='Rol que determina los permisos del usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.rolusuario', verbose_name='Rol del Usuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'ordering': ['-date_joined'],
            },
        ),
    ]
