# Generated by Django 5.2.1 on 2025-11-21 02:00

import apps.registro.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('nombre_fantasia', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de Fantasía')),
                ('tipo_sociedad', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Sociedad')),
                ('cuit_cuil', models.CharField(help_text='Ingrese el CUIT/CUIL', max_length=15, verbose_name='CUIT/CUIL')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal')),
                ('provincia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia')),
                ('departamento', models.CharField(max_length=100, verbose_name='Departamento')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('localidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad')),
                ('geolocalizacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Geolocalización')),
                ('telefono', models.CharField(help_text='Formato: +54 9 11 1234-5678', max_length=20, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('sitioweb', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('tipo_empresa', models.CharField(choices=[('producto', 'Solo Productos'), ('servicio', 'Solo Servicios'), ('mixta', 'Productos y Servicios')], max_length=20, verbose_name='Tipo de Empresa')),
                ('rubro_principal', models.CharField(max_length=100, verbose_name='Rubro Principal')),
                ('sub_rubro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Rubro')),
                ('rubro_producto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro de Productos')),
                ('sub_rubro_producto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Rubro de Productos')),
                ('rubro_servicio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro de Servicios')),
                ('sub_rubro_servicio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Rubro de Servicios')),
                ('descripcion_actividad', models.TextField(blank=True, null=True, verbose_name='Descripción de la Actividad')),
                ('productos', models.JSONField(blank=True, default=list, verbose_name='Productos')),
                ('servicios_ofrecidos', models.JSONField(blank=True, default=dict, null=True, verbose_name='Servicios Ofrecidos')),
                ('actividades_promocion', models.JSONField(blank=True, default=list, verbose_name='Actividades de Promoción')),
                ('contactos_secundarios', models.JSONField(blank=True, default=list, verbose_name='Contactos Secundarios')),
                ('instagram', models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram')),
                ('facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn')),
                ('exporta', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('en-proceso', 'En proceso')], max_length=20, null=True, verbose_name='¿Exporta productos/servicios?')),
                ('destino_exportacion', models.TextField(blank=True, null=True, verbose_name='Principales destinos de exportación')),
                ('importa', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=10, null=True, verbose_name='¿Importa productos/servicios?')),
                ('tipo_importacion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tipo de importación')),
                ('certificado_pyme', models.CharField(blank=True, choices=[('si', 'Sí, vigente'), ('vencido', 'Sí, vencido'), ('en-tramite', 'En trámite'), ('no', 'No')], max_length=20, null=True, verbose_name='¿Tiene certificado MiPYME?')),
                ('certificaciones', models.TextField(blank=True, null=True, verbose_name='Certificaciones (ISO, etc.)')),
                ('brochure_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='URL del Brochure')),
                ('catalogo_pdf', models.FileField(blank=True, help_text='Subir catálogo o brochure en formato PDF', null=True, upload_to=apps.registro.models.generar_nombre_catalogo_solicitud, verbose_name='Catálogo en PDF')),
                ('catalogo_pdf_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Archivo PDF')),
                ('material_promocional_idiomas', models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('en-desarrollo', 'En desarrollo')], max_length=20, null=True, verbose_name='¿Tiene material promocional en otros idiomas?')),
                ('idiomas_trabajo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Idiomas en los que trabaja')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones Generales')),
                ('nombre_contacto', models.CharField(max_length=100, verbose_name='Nombre del Contacto')),
                ('cargo_contacto', models.CharField(max_length=100, verbose_name='Cargo del Contacto')),
                ('telefono_contacto', models.CharField(max_length=20, verbose_name='Teléfono del Contacto')),
                ('email_contacto', models.EmailField(max_length=254, verbose_name='Email del Contacto')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('en_revision', 'En Revisión')], default='pendiente', max_length=20, verbose_name='Estado de la Solicitud')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación')),
                ('observaciones_admin', models.TextField(blank=True, null=True, verbose_name='Observaciones del Administrador')),
                ('token_confirmacion', models.CharField(max_length=100, unique=True, verbose_name='Token de Confirmación')),
                ('email_confirmado', models.BooleanField(default=False, verbose_name='Email Confirmado')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa_creada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa', verbose_name='Empresa Creada')),
                ('usuario_creado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_registro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creado')),
            ],
            options={
                'verbose_name': 'Solicitud de Registro',
                'verbose_name_plural': 'Solicitudes de Registro',
                'db_table': 'solicitud_registro',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('confirmacion', 'Confirmación de Email'), ('aprobacion', 'Aprobación de Solicitud'), ('rechazo', 'Rechazo de Solicitud'), ('recordatorio', 'Recordatorio')], max_length=20, verbose_name='Tipo de Notificación')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email Enviado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Envío')),
                ('error_envio', models.TextField(blank=True, null=True, verbose_name='Error de Envío')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='registro.solicitudregistro', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Notificación de Registro',
                'verbose_name_plural': 'Notificaciones de Registro',
                'db_table': 'notificacion_registro',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoSolicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('cuit', 'Constancia de CUIT'), ('acta', 'Acta Constitutiva'), ('estatutos', 'Estatutos'), ('certificado', 'Certificado'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('archivo', models.FileField(upload_to='solicitudes/documentos/', verbose_name='Archivo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='registro.solicitudregistro', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Documento de Solicitud',
                'verbose_name_plural': 'Documentos de Solicitud',
                'db_table': 'documento_solicitud',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='solicitudregistro',
            index=models.Index(fields=['estado'], name='solicitud_r_estado_fabd05_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudregistro',
            index=models.Index(fields=['tipo_empresa'], name='solicitud_r_tipo_em_560042_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudregistro',
            index=models.Index(fields=['fecha_creacion'], name='solicitud_r_fecha_c_c68fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudregistro',
            index=models.Index(fields=['token_confirmacion'], name='solicitud_r_token_c_fcc0b7_idx'),
        ),
    ]
