# Generated by Django 5.2.1 on 2025-11-04 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistro',
            name='actividades_promocion',
            field=models.JSONField(blank=True, default=list, verbose_name='Actividades de Promoción'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='brochure_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL del Brochure'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='contactos_secundarios',
            field=models.JSONField(blank=True, default=list, verbose_name='Contactos Secundarios'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='geolocalizacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Geolocalización'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de Fantasía'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Generales'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='productos',
            field=models.JSONField(blank=True, default=list, verbose_name='Productos'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='servicios_ofrecidos',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Servicios Ofrecidos'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='sub_rubro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Rubro'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='tipo_sociedad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Sociedad'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='usuario_creado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitud_registro', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creado'),
        ),
        migrations.AlterField(
            model_name='solicitudregistro',
            name='certificado_pyme',
            field=models.CharField(blank=True, choices=[('si', 'Sí, vigente'), ('vencido', 'Sí, vencido'), ('en-tramite', 'En trámite'), ('no', 'No')], max_length=20, null=True, verbose_name='¿Tiene certificado MiPYME?'),
        ),
        migrations.AlterField(
            model_name='solicitudregistro',
            name='cuit_cuil',
            field=models.CharField(help_text='Ingrese el CUIT/CUIL', max_length=15, verbose_name='CUIT/CUIL'),
        ),
        migrations.AlterField(
            model_name='solicitudregistro',
            name='destino_exportacion',
            field=models.TextField(blank=True, null=True, verbose_name='Principales destinos de exportación'),
        ),
        migrations.AlterField(
            model_name='solicitudregistro',
            name='exporta',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('en-proceso', 'En proceso')], max_length=20, null=True, verbose_name='¿Exporta productos/servicios?'),
        ),
        migrations.AlterField(
            model_name='solicitudregistro',
            name='idiomas_trabajo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Idiomas en los que trabaja'),
        ),
        migrations.AlterField(
            model_name='solicitudregistro',
            name='importa',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No')], max_length=10, null=True, verbose_name='¿Importa productos/servicios?'),
        ),
        migrations.AlterField(
            model_name='solicitudregistro',
            name='material_promocional_idiomas',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('en-desarrollo', 'En desarrollo')], max_length=20, null=True, verbose_name='¿Tiene material promocional en otros idiomas?'),
        ),
    ]
