# Generated by Django 5.2.1 on 2025-11-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudregistro',
            name='provincia',
        ),
    ]
