# Generated by Django 5.2.1 on 2025-11-27 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_remove_solicitudregistro_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistro',
            name='codigo_postal_comercial',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal Comercial'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='direccion_comercial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Comercial'),
        ),
    ]
