# Generated by Django 5.2.1 on 2025-11-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_solicitudregistro_actividades_promocion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudregistro',
            name='descripcion_actividad',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la Actividad'),
        ),
    ]
