# Generated by Django 5.2.1 on 2025-11-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_alter_solicitudregistro_descripcion_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistro',
            name='catalogo_pdf',
            field=models.FileField(blank=True, help_text='Subir catálogo o brochure en formato PDF', null=True, upload_to='catalogos/%Y/%m/', verbose_name='Catálogo en PDF'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='catalogo_pdf_nombre',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Archivo PDF'),
        ),
    ]
