# Generated by Django 5.2.1 on 2025-12-17 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_solicitudregistro_codigo_postal_comercial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistro',
            name='interes_exportar',
            field=models.BooleanField(blank=True, help_text='Solo aplica si NO exporta actualmente', null=True, verbose_name='¿Está Interesada en Comenzar a Exportar?'),
        ),
    ]
