# Generated by Django 5.2.1 on 2025-11-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresamixta_empresaproducto_empresaservicio'),
        ('registro', '0004_solicitudregistro_catalogo_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudregistro',
            name='empresa_creada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa', verbose_name='Empresa Creada'),
        ),
    ]
