# Generated by Django 5.2.1 on 2025-11-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_corregir_fk_empresa_creada'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudregistro',
            name='rubro_producto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro de Productos'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='rubro_servicio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rubro de Servicios'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='sub_rubro_producto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Rubro de Productos'),
        ),
        migrations.AddField(
            model_name='solicitudregistro',
            name='sub_rubro_servicio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub-Rubro de Servicios'),
        ),
    ]
