# Generated by Django 5.2.1 on 2025-10-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaArchivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255, verbose_name='Nombre del Archivo')),
                ('ruta_archivo', models.CharField(max_length=500, verbose_name='Ruta del Archivo')),
                ('tamaño_archivo', models.BigIntegerField(blank=True, null=True, verbose_name='Tamaño del Archivo (bytes)')),
                ('tipo_archivo', models.CharField(max_length=50, verbose_name='Tipo de Archivo')),
                ('hash_archivo', models.CharField(blank=True, help_text='Hash SHA-256 para verificar integridad', max_length=64, null=True, verbose_name='Hash del Archivo')),
            ],
            options={
                'verbose_name': 'Archivo Auditado',
                'verbose_name_plural': 'Archivos Auditados',
                'db_table': 'auditoria_archivos',
                'ordering': ['-auditoria_log__timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaCambios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_modificado', models.CharField(max_length=100, verbose_name='Campo Modificado')),
                ('valor_anterior', models.TextField(blank=True, null=True, verbose_name='Valor Anterior')),
                ('valor_nuevo', models.TextField(blank=True, null=True, verbose_name='Valor Nuevo')),
            ],
            options={
                'verbose_name': 'Cambio Detallado',
                'verbose_name_plural': 'Cambios Detallados',
                'db_table': 'auditoria_cambios',
                'ordering': ['campo_modificado'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True, verbose_name='Clave de Sesión')),
                ('user_agent', models.TextField(blank=True, help_text='Información del navegador/dispositivo', null=True, verbose_name='User Agent')),
                ('accion', models.CharField(choices=[('CREATE', 'Crear'), ('READ', 'Leer'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('LOGIN', 'Iniciar Sesión'), ('LOGOUT', 'Cerrar Sesión'), ('EXPORT', 'Exportar'), ('IMPORT', 'Importar'), ('LOGIN_FAILED', 'Intento de Login Fallido'), ('PASSWORD_CHANGE', 'Cambio de Contraseña'), ('PASSWORD_RESET', 'Restablecer Contraseña'), ('PERMISSION_DENIED', 'Acceso Denegado'), ('FILE_UPLOAD', 'Subir Archivo'), ('FILE_DOWNLOAD', 'Descargar Archivo'), ('EMAIL_SENT', 'Email Enviado'), ('EMAIL_FAILED', 'Email Fallido'), ('SYSTEM_ERROR', 'Error del Sistema')], max_length=50, verbose_name='Acción Realizada')),
                ('modelo_afectado', models.CharField(help_text='Nombre del modelo Django afectado', max_length=100, verbose_name='Modelo Afectado')),
                ('objeto_id', models.PositiveIntegerField(blank=True, help_text='ID del objeto específico afectado', null=True, verbose_name='ID del Objeto')),
                ('nombre_objeto', models.CharField(blank=True, help_text='Nombre descriptivo del objeto (ej: razón social de empresa)', max_length=200, null=True, verbose_name='Nombre del Objeto')),
                ('descripcion', models.TextField(help_text='Descripción detallada de la acción realizada', verbose_name='Descripción')),
                ('detalles_adicionales', models.JSONField(blank=True, default=dict, help_text='Información adicional en formato JSON', verbose_name='Detalles Adicionales')),
                ('valores_anteriores', models.JSONField(blank=True, default=dict, help_text='Valores del objeto antes del cambio', verbose_name='Valores Anteriores')),
                ('valores_nuevos', models.JSONField(blank=True, default=dict, help_text='Valores del objeto después del cambio', verbose_name='Valores Nuevos')),
                ('url', models.URLField(blank=True, help_text='URL donde se realizó la acción', null=True, verbose_name='URL')),
                ('metodo_http', models.CharField(blank=True, help_text='GET, POST, PUT, DELETE, etc.', max_length=10, null=True, verbose_name='Método HTTP')),
                ('nivel_criticidad', models.CharField(choices=[('INFO', 'Informativo'), ('WARNING', 'Advertencia'), ('ERROR', 'Error'), ('CRITICAL', 'Crítico')], default='INFO', max_length=20, verbose_name='Nivel de Criticidad')),
                ('categoria', models.CharField(choices=[('AUTHENTICATION', 'Autenticación'), ('USER_MANAGEMENT', 'Gestión de Usuarios'), ('COMPANY_MANAGEMENT', 'Gestión de Empresas'), ('DATA_EXPORT', 'Exportación de Datos'), ('DATA_IMPORT', 'Importación de Datos'), ('FILE_MANAGEMENT', 'Gestión de Archivos'), ('SYSTEM_ADMIN', 'Administración del Sistema'), ('SECURITY', 'Seguridad'), ('ERROR', 'Errores')], max_length=50, verbose_name='Categoría')),
                ('exito', models.BooleanField(default=True, help_text='Indica si la acción fue exitosa', verbose_name='Éxito')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si la acción falló', null=True, verbose_name='Mensaje de Error')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'auditoria_log',
                'ordering': ['-timestamp'],
            },
        ),
    ]
