# Generated by Django 5.2.1 on 2025-11-16 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('centroide_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud Centroide')),
                ('centroide_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud Centroide')),
                ('geometria', models.JSONField(blank=True, null=True, verbose_name='Geometría')),
                ('fuente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'geografia_ar_departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('iso_id', models.CharField(max_length=5, verbose_name='ISO ID')),
                ('iso_nombre', models.CharField(max_length=100, verbose_name='ISO Nombre')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('centroide_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud Centroide')),
                ('centroide_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud Centroide')),
                ('geometria', models.JSONField(blank=True, null=True, verbose_name='Geometría')),
                ('fuente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'geografia_ar_provincias',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['nombre'], name='geografia_a_nombre_6897ab_idx'), models.Index(fields=['iso_id'], name='geografia_a_iso_id_d62495_idx'), models.Index(fields=['centroide_lat', 'centroide_lon'], name='geografia_a_centroi_311d03_idx')],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('categoria', models.CharField(max_length=50, verbose_name='Categoría')),
                ('centroide_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud Centroide')),
                ('centroide_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud Centroide')),
                ('geometria', models.JSONField(blank=True, null=True, verbose_name='Geometría')),
                ('fuente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='municipios', to='geografia.departamento', verbose_name='Departamento')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipios', to='geografia.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'geografia_ar_municipios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('tipo_asentamiento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Asentamiento')),
                ('centroide_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Latitud Centroide')),
                ('centroide_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Longitud Centroide')),
                ('geometria', models.JSONField(blank=True, null=True, verbose_name='Geometría')),
                ('fuente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuente')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='geografia.departamento', verbose_name='Departamento')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localidades', to='geografia.municipio', verbose_name='Municipio')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localidades', to='geografia.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
                'db_table': 'geografia_ar_localidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='departamento',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='geografia.provincia', verbose_name='Provincia'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['provincia'], name='geografia_a_provinc_eb134f_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['departamento'], name='geografia_a_departa_15734d_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['nombre'], name='geografia_a_nombre_70a276_idx'),
        ),
        migrations.AddIndex(
            model_name='municipio',
            index=models.Index(fields=['centroide_lat', 'centroide_lon'], name='geografia_a_centroi_5e20c8_idx'),
        ),
        migrations.AddIndex(
            model_name='localidad',
            index=models.Index(fields=['provincia'], name='geografia_a_provinc_d77ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='localidad',
            index=models.Index(fields=['departamento'], name='geografia_a_departa_99a5b1_idx'),
        ),
        migrations.AddIndex(
            model_name='localidad',
            index=models.Index(fields=['municipio'], name='geografia_a_municip_693e5e_idx'),
        ),
        migrations.AddIndex(
            model_name='localidad',
            index=models.Index(fields=['nombre'], name='geografia_a_nombre_9737d5_idx'),
        ),
        migrations.AddIndex(
            model_name='localidad',
            index=models.Index(fields=['tipo_asentamiento'], name='geografia_a_tipo_as_b75b07_idx'),
        ),
        migrations.AddIndex(
            model_name='localidad',
            index=models.Index(fields=['centroide_lat', 'centroide_lon'], name='geografia_a_centroi_05dd0a_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['provincia'], name='geografia_a_provinc_c14f4b_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['nombre'], name='geografia_a_nombre_4a2190_idx'),
        ),
        migrations.AddIndex(
            model_name='departamento',
            index=models.Index(fields=['centroide_lat', 'centroide_lon'], name='geografia_a_centroi_8385bb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nombre', 'provincia')},
        ),
    ]
