# Generated by Django 5.2.1 on 2025-11-15 14:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('empresas', '0001_initial'),
        ('registro', '0004_solicitudregistro_catalogo_pdf_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # NO remover campos todavía - se necesitan para la migración de datos en 0003
        # Se removerán en 0004 antes de eliminar las tablas antiguas
        # migrations.RemoveField(
        #     model_name='empresamixta',
        #     name='actualizado_por',
        # ),
        # migrations.RemoveField(
        #     model_name='empresamixta',
        #     name='creado_por',
        # ),
        # migrations.RemoveField(
        #     model_name='empresamixta',
        #     name='departamento',
        # ),
        # migrations.RemoveField(
        #     model_name='empresamixta',
        #     name='id_rubro',
        # ),
        # migrations.RemoveField(
        #     model_name='empresamixta',
        #     name='id_usuario',
        # ),
        # migrations.RemoveField(
        #     model_name='empresamixta',
        #     name='localidad',
        # ),
        # migrations.RemoveField(
        #     model_name='empresamixta',
        #     name='municipio',
        # ),
        # migrations.RemoveField(
        #     model_name='empresamixta',
        #     name='tipo_empresa',
        # ),
        migrations.RemoveField(
            model_name='matrizclasificacionexportador',
            name='empresa_mixta',
        ),
        # NO remover campos todavía - se necesitan para la migración de datos en 0003
        # migrations.RemoveField(
        #     model_name='empresaproducto',
        #     name='actualizado_por',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaproducto',
        #     name='creado_por',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaproducto',
        #     name='departamento',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaproducto',
        #     name='id_rubro',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaproducto',
        #     name='id_usuario',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaproducto',
        #     name='localidad',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaproducto',
        #     name='municipio',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaproducto',
        #     name='tipo_empresa',
        # ),
        migrations.RemoveField(
            model_name='matrizclasificacionexportador',
            name='empresa_producto',
        ),
        # NO remover campos todavía - se necesitan para la migración de datos en 0003
        # migrations.RemoveField(
        #     model_name='empresaservicio',
        #     name='actualizado_por',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaservicio',
        #     name='creado_por',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaservicio',
        #     name='departamento',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaservicio',
        #     name='id_rubro',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaservicio',
        #     name='id_usuario',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaservicio',
        #     name='localidad',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaservicio',
        #     name='municipio',
        # ),
        # migrations.RemoveField(
        #     model_name='empresaservicio',
        #     name='tipo_empresa',
        # ),
        migrations.RemoveField(
            model_name='matrizclasificacionexportador',
            name='empresa_servicio',
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('cuit_cuil', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CUIT debe tener exactamente 11 dígitos', regex='^\\d{11}$')], verbose_name='CUIT/CUIL')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('geolocalizacion', models.CharField(blank=True, max_length=2083, null=True, verbose_name='Geolocalización')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono Principal')),
                ('correo', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico Principal')),
                ('sitioweb', models.URLField(blank=True, null=True, verbose_name='Sitio Web')),
                ('email_secundario', models.EmailField(blank=True, help_text='Email adicional de la empresa (opcional)', max_length=254, null=True, verbose_name='Email Secundario')),
                ('email_terciario', models.EmailField(blank=True, help_text='Tercer email de la empresa (opcional)', max_length=254, null=True, verbose_name='Email Terciario')),
                ('contacto_principal_nombre', models.CharField(help_text='Nombre del contacto principal de la empresa (OBLIGATORIO)', max_length=100, verbose_name='Nombre del Contacto Principal')),
                ('contacto_principal_cargo', models.CharField(help_text='Cargo del contacto principal (OBLIGATORIO)', max_length=100, verbose_name='Cargo del Contacto Principal')),
                ('contacto_principal_telefono', models.CharField(help_text='Teléfono del contacto principal (OBLIGATORIO)', max_length=20, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono del Contacto Principal')),
                ('contacto_principal_email', models.EmailField(help_text='Email del contacto principal (OBLIGATORIO)', max_length=254, verbose_name='Email del Contacto Principal')),
                ('contacto_secundario_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Contacto Secundario')),
                ('contacto_secundario_cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Contacto Secundario')),
                ('contacto_secundario_telefono', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono del Contacto Secundario')),
                ('contacto_secundario_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Contacto Secundario')),
                ('exporta', models.CharField(blank=True, choices=[('Sí', 'Sí'), ('No, solo ventas nacionales', 'No, solo ventas nacionales'), ('No, solo ventas locales', 'No, solo ventas locales')], help_text='Seleccione el tipo de ventas que realiza la empresa', max_length=50, null=True, verbose_name='¿La Empresa Exporta?')),
                ('destinoexporta', models.CharField(blank=True, help_text='Si exporta, indique los destinos. Si son varios, sepárelos por comas.', max_length=200, null=True, verbose_name='Destinos de Exportación')),
                ('tipoexporta', models.CharField(blank=True, choices=[('Directa', 'Directa'), ('Terceros', 'A través de Terceros'), ('Mixta', 'Mixta')], max_length=50, null=True, verbose_name='Tipo de Exportación')),
                ('interes_exportar', models.BooleanField(blank=True, help_text='Marque si la empresa está interesada en comenzar a exportar', null=True, verbose_name='¿Está Interesada en Comenzar a Exportar?')),
                ('importa', models.BooleanField(blank=True, help_text='Marque si la empresa realiza importaciones', null=True, verbose_name='¿La Empresa Realiza Importaciones?')),
                ('tipoimporta', models.CharField(blank=True, help_text='Si importa, indique los tipos. Si son varios, sepárelos por comas.', max_length=200, null=True, verbose_name='Tipos de Importación')),
                ('otrasimportaciones', models.CharField(blank=True, help_text="Si seleccionó 'Otros' en tipos de importación, detalle cuáles", max_length=200, null=True, verbose_name='Otras Importaciones')),
                ('frecuenciaimporta', models.CharField(blank=True, choices=[('Mensual', 'Mensual'), ('Anual', 'Anual'), ('Ocasional', 'De manera ocasional'), ('Nunca', 'Nunca realicé importaciones')], max_length=50, null=True, verbose_name='Frecuencia de Importación')),
                ('certificadopyme', models.BooleanField(blank=True, help_text='Marque si la empresa posee certificado MiPYME', null=True, verbose_name='¿Posee Certificado MiPYME?')),
                ('certificacionesbool', models.BooleanField(blank=True, help_text='Marque si la empresa posee certificaciones internacionales', null=True, verbose_name='¿Posee Certificaciones Internacionales?')),
                ('certificaciones', models.CharField(blank=True, help_text='Si posee certificaciones, detalle cuáles. Si son varias, sepárelas por comas.', max_length=300, null=True, verbose_name='Detalle de Certificaciones')),
                ('certificaciones_otros', models.CharField(blank=True, help_text="Si seleccionó 'Otra' en certificaciones, detalle cuáles", max_length=300, null=True, verbose_name='Otras Certificaciones')),
                ('archivo_certificaciones', models.FileField(blank=True, help_text='Subir archivo PDF o imagen de las certificaciones', null=True, upload_to='certificaciones/%Y/%m/', verbose_name='Archivo de Certificaciones')),
                ('archivo_certificaciones_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Archivo de Certificaciones')),
                ('promo2idiomas', models.BooleanField(blank=True, help_text='Marque si la empresa posee material de promoción en más de un idioma', null=True, verbose_name='¿Posee Material de Promoción en Más de un Idioma?')),
                ('idiomas_trabaja', models.CharField(blank=True, help_text='Si posee material en más de un idioma, indique cuáles. Si son varios, sepárelos por comas.', max_length=100, null=True, verbose_name='Idiomas con los que Trabaja')),
                ('capacidadproductiva', models.DecimalField(blank=True, decimal_places=2, help_text='Capacidad productiva de la empresa', max_digits=10, null=True, verbose_name='Capacidad Productiva')),
                ('tiempocapacidad', models.CharField(blank=True, choices=[('Mensual', 'Mensual'), ('Anual', 'Anual'), ('Semanal', 'Semanal')], max_length=20, null=True, verbose_name='Período de la Capacidad Productiva')),
                ('otracapacidad', models.TextField(blank=True, help_text='Si posee otro producto con diferente capacidad productiva, indíquelo aquí', null=True, verbose_name='Otra Capacidad Productiva')),
                ('redes_sociales', models.TextField(blank=True, help_text='URLs o texto separado por comas', null=True, verbose_name='Redes Sociales')),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de latitud (se llena automáticamente al seleccionar en el mapa)', max_digits=10, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, help_text='Coordenada de longitud (se llena automáticamente al seleccionar en el mapa)', max_digits=11, null=True, verbose_name='Longitud')),
                ('participoferianacional', models.BooleanField(blank=True, help_text='Marque si la empresa participó en ferias nacionales', null=True, verbose_name='¿Participó en Ferias Nacionales?')),
                ('feriasnacionales', models.TextField(blank=True, help_text='Si participó, detalle nombre, lugar y año. Si son varias, sepárelas por comas.', null=True, verbose_name='Detalle de Ferias Nacionales')),
                ('participoferiainternacional', models.BooleanField(blank=True, help_text='Marque si la empresa participó en ferias internacionales', null=True, verbose_name='¿Participó en Ferias Internacionales?')),
                ('feriasinternacionales', models.TextField(blank=True, help_text='Si participó, detalle nombre, lugar y año. Si son varias, sepárelas por comas.', null=True, verbose_name='Detalle de Ferias Internacionales')),
                ('archivo_ferias', models.FileField(blank=True, help_text='Subir archivo PDF o imagen de participación en ferias', null=True, upload_to='ferias/%Y/%m/', verbose_name='Archivo de Ferias')),
                ('archivo_ferias_nombre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre del Archivo de Ferias')),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observaciones')),
                ('puntaje', models.IntegerField(blank=True, null=True, verbose_name='Puntaje')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/%Y/%m/', verbose_name='Logo de la Empresa')),
                ('brochure', models.FileField(blank=True, help_text='Subir archivo PDF o imagen del brochure/catálogo', null=True, upload_to='brochures/%Y/%m/', verbose_name='Brochure o Catálogo')),
                ('descripcion', models.TextField(blank=True, help_text='Describa brevemente los productos/servicios de la empresa', null=True, verbose_name='Descripción de la Empresa')),
                ('tipo_empresa_valor', models.CharField(choices=[('producto', 'Solo Productos'), ('servicio', 'Solo Servicios'), ('mixta', 'Productos y Servicios')], help_text='Tipo de empresa: solo productos, solo servicios, o mixta', max_length=20, verbose_name='Tipo de Empresa')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dpto', verbose_name='Departamento')),
                ('id_rubro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.rubro', verbose_name='Rubro')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.localidades', verbose_name='Localidad')),
                ('municipio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.municipio', verbose_name='Municipio')),
                ('tipo_empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empresas.tipoempresa', verbose_name='Tipo de Empresa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='matrizclasificacionexportador',
            name='empresa',
            field=models.ForeignKey(blank=True, help_text='Empresa a la que se aplica esta clasificación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones_exportador', to='empresas.empresa', verbose_name='Empresa'),
        ),
        # NO cambiar las ForeignKeys todavía - se hará después de migrar los datos
        # migrations.AlterField(...) - Comentado temporalmente
        migrations.AddConstraint(
            model_name='matrizclasificacionexportador',
            constraint=models.UniqueConstraint(fields=('empresa',), name='unique_matriz_empresa'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['razon_social'], name='empresa_razon_s_5d5262_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['cuit_cuil'], name='empresa_cuit_cu_232997_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['departamento', 'municipio'], name='empresa_departa_508358_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['fecha_creacion'], name='empresa_fecha_c_ca3475_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['exporta', 'importa'], name='empresa_exporta_2b4df4_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['exporta'], name='empresa_exporta_79a94b_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['importa'], name='empresa_importa_b06ba1_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['certificadopyme'], name='empresa_certifi_194626_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['certificacionesbool'], name='empresa_certifi_70c048_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['participoferianacional'], name='empresa_partici_642dae_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['participoferiainternacional'], name='empresa_partici_da90a5_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['promo2idiomas'], name='empresa_promo2i_823736_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['capacidadproductiva'], name='empresa_capacid_01dd86_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['tiempocapacidad'], name='empresa_tiempoc_e5b959_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['puntaje'], name='empresa_puntaje_710e33_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['latitud', 'longitud'], name='empresa_latitud_24d0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['tipo_empresa'], name='empresa_tipo_em_83d814_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['tipo_empresa_valor'], name='empresa_tipo_em_7ec7af_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['id_rubro'], name='empresa_id_rubr_6d259c_idx'),
        ),
        # NO eliminar las tablas antiguas todavía - se hará después de migrar los datos
        # migrations.DeleteModel(...) - Comentado temporalmente
        migrations.CreateModel(
            name='Empresaproducto',
            fields=[
            ],
            options={
                'verbose_name': 'Empresa de Producto',
                'verbose_name_plural': 'Empresas de Productos',
                'ordering': ['-fecha_creacion'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.empresa',),
        ),
        migrations.CreateModel(
            name='Empresaservicio',
            fields=[
            ],
            options={
                'verbose_name': 'Empresa de Servicio',
                'verbose_name_plural': 'Empresas de Servicios',
                'ordering': ['-fecha_creacion'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.empresa',),
        ),
        migrations.CreateModel(
            name='EmpresaMixta',
            fields=[
            ],
            options={
                'verbose_name': 'Empresa Mixta',
                'verbose_name_plural': 'Empresas Mixtas',
                'ordering': ['-fecha_creacion'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.empresa',),
        ),
    ]
