# Generated by Django 5.2.1 on 2025-11-27 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('geografia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='geografia.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='geografia.localidad', verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='municipio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas', to='geografia.municipio', verbose_name='Municipio'),
        ),
    ]
