# Generated by Django 5.2.1 on 2025-11-27 12:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_alter_empresa_departamento_alter_empresa_localidad_and_more'),
        ('geografia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='empresa',
            name='empresa_departa_508358_idx',
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre_fantasia',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nombre de Fantasía'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_sociedad',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Sociedad'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['departamento', 'municipio', 'localidad'], name='empresa_departa_f85dc5_idx'),
        ),
    ]
