# Generated by Django 5.2.1 on 2025-11-15 14:15

from django.db import migrations, models
import django.db.models.deletion

def migrar_datos_empresas(apps, schema_editor):
    """
    Migra datos de empresaproducto, empresaservicio, empresa_mixta a la nueva tabla empresa usando SQL directo
    Primero asegura que las tablas antiguas tengan los campos de auditoría
    """
    db = schema_editor.connection.alias
    
    with schema_editor.connection.cursor() as cursor:
        # 0. Verificar y agregar TODOS los campos necesarios a las tablas antiguas si no existen
        # Esto es necesario porque la migración 0002 puede haber removido algunos campos
        # y TODAS las tablas deben tener auditorías
        campos_necesarios = [
            ('actualizado_por_id', 'BIGINT'),
            ('creado_por_id', 'BIGINT'),
            ('departamento_id', 'BIGINT'),
            ('id_rubro_id', 'BIGINT'),
            ('id_usuario_id', 'BIGINT'),
            ('localidad_id', 'BIGINT'),
            ('municipio_id', 'BIGINT'),
            ('tipo_empresa_id', 'BIGINT'),
        ]
        
        for tabla in ['empresaproducto', 'empresaservicio', 'empresa_mixta']:
            for campo, tipo in campos_necesarios:
                cursor.execute(f"""
                    SELECT column_name 
                    FROM information_schema.columns 
                    WHERE table_name = '{tabla}' 
                    AND column_name = '{campo}'
                """)
                if not cursor.fetchone():
                    try:
                        cursor.execute(f"""
                            ALTER TABLE {tabla} 
                            ADD COLUMN {campo} {tipo} NULL
                        """)
                    except Exception as e:
                        # Si falla, puede ser que la columna ya exista o haya otro problema
                        print(f"Warning: No se pudo agregar {campo} a {tabla}: {e}")
        
        # 1. Copiar empresas de producto (mantienen su ID)
        cursor.execute("""
            INSERT INTO empresa (
                id, fecha_creacion, fecha_actualizacion, razon_social, cuit_cuil,
                direccion, geolocalizacion, telefono, correo, sitioweb,
                email_secundario, email_terciario,
                contacto_principal_nombre, contacto_principal_cargo,
                contacto_principal_telefono, contacto_principal_email,
                contacto_secundario_nombre, contacto_secundario_cargo,
                contacto_secundario_telefono, contacto_secundario_email,
                exporta, destinoexporta, tipoexporta, interes_exportar,
                importa, tipoimporta, otrasimportaciones, frecuenciaimporta,
                certificadopyme, certificacionesbool, certificaciones, certificaciones_otros,
                archivo_certificaciones, archivo_certificaciones_nombre,
                promo2idiomas, idiomas_trabaja,
                capacidadproductiva, tiempocapacidad, otracapacidad,
                redes_sociales, latitud, longitud,
                participoferianacional, feriasnacionales,
                participoferiainternacional, feriasinternacionales,
                archivo_ferias, archivo_ferias_nombre,
                observaciones, puntaje, logo, brochure, descripcion,
                tipo_empresa_valor,
                actualizado_por_id, creado_por_id,
                departamento_id, id_rubro_id, id_usuario_id,
                localidad_id, municipio_id, tipo_empresa_id
            )
            SELECT 
                id, fecha_creacion, fecha_actualizacion, razon_social, cuit_cuil,
                direccion, geolocalizacion, telefono, correo, sitioweb,
                email_secundario, email_terciario,
                contacto_principal_nombre, contacto_principal_cargo,
                contacto_principal_telefono, contacto_principal_email,
                contacto_secundario_nombre, contacto_secundario_cargo,
                contacto_secundario_telefono, contacto_secundario_email,
                exporta, destinoexporta, tipoexporta, interes_exportar,
                importa, tipoimporta, otrasimportaciones, frecuenciaimporta,
                certificadopyme, certificacionesbool, certificaciones, certificaciones_otros,
                archivo_certificaciones, archivo_certificaciones_nombre,
                promo2idiomas, idiomas_trabaja,
                capacidadproductiva, tiempocapacidad, otracapacidad,
                redes_sociales, latitud, longitud,
                participoferianacional, feriasnacionales,
                participoferiainternacional, feriasinternacionales,
                archivo_ferias, archivo_ferias_nombre,
                observaciones, puntaje, logo, brochure, descripcion,
                'producto' as tipo_empresa_valor,
                actualizado_por_id,
                creado_por_id,
                departamento_id, id_rubro_id, id_usuario_id,
                localidad_id, municipio_id, tipo_empresa_id
            FROM empresaproducto
            WHERE NOT EXISTS (SELECT 1 FROM empresa WHERE empresa.id = empresaproducto.id)
            AND departamento_id IS NOT NULL
            AND id_rubro_id IS NOT NULL
            AND id_usuario_id IS NOT NULL
            AND tipo_empresa_id IS NOT NULL
        """)
        
        # 2. Obtener el siguiente ID disponible para servicios
        cursor.execute("SELECT COALESCE(MAX(id), 0) FROM empresa")
        max_id = cursor.fetchone()[0]
        
        # 3. Copiar empresas de servicio (con nuevos IDs únicos)
        cursor.execute(f"""
            INSERT INTO empresa (
                id, fecha_creacion, fecha_actualizacion, razon_social, cuit_cuil,
                direccion, geolocalizacion, telefono, correo, sitioweb,
                email_secundario, email_terciario,
                contacto_principal_nombre, contacto_principal_cargo,
                contacto_principal_telefono, contacto_principal_email,
                contacto_secundario_nombre, contacto_secundario_cargo,
                contacto_secundario_telefono, contacto_secundario_email,
                exporta, destinoexporta, tipoexporta, interes_exportar,
                importa, tipoimporta, otrasimportaciones, frecuenciaimporta,
                certificadopyme, certificacionesbool, certificaciones, certificaciones_otros,
                archivo_certificaciones, archivo_certificaciones_nombre,
                promo2idiomas, idiomas_trabaja,
                capacidadproductiva, tiempocapacidad, otracapacidad,
                redes_sociales, latitud, longitud,
                participoferianacional, feriasnacionales,
                participoferiainternacional, feriasinternacionales,
                archivo_ferias, archivo_ferias_nombre,
                observaciones, puntaje, logo, brochure, descripcion,
                tipo_empresa_valor,
                actualizado_por_id, creado_por_id,
                departamento_id, id_rubro_id, id_usuario_id,
                localidad_id, municipio_id, tipo_empresa_id
            )
            SELECT 
                (ROW_NUMBER() OVER (ORDER BY id) + {max_id}) as id,
                fecha_creacion, fecha_actualizacion, razon_social, cuit_cuil,
                direccion, geolocalizacion, telefono, correo, sitioweb,
                email_secundario, email_terciario,
                contacto_principal_nombre, contacto_principal_cargo,
                contacto_principal_telefono, contacto_principal_email,
                contacto_secundario_nombre, contacto_secundario_cargo,
                contacto_secundario_telefono, contacto_secundario_email,
                exporta, destinoexporta, tipoexporta, interes_exportar,
                importa, tipoimporta, otrasimportaciones, frecuenciaimporta,
                certificadopyme, certificacionesbool, certificaciones, certificaciones_otros,
                archivo_certificaciones, archivo_certificaciones_nombre,
                promo2idiomas, idiomas_trabaja,
                capacidadproductiva, tiempocapacidad, otracapacidad,
                redes_sociales, latitud, longitud,
                participoferianacional, feriasnacionales,
                participoferiainternacional, feriasinternacionales,
                archivo_ferias, archivo_ferias_nombre,
                observaciones, puntaje, logo, brochure, descripcion,
                'servicio' as tipo_empresa_valor,
                actualizado_por_id,
                creado_por_id,
                departamento_id, id_rubro_id, id_usuario_id,
                localidad_id, municipio_id, tipo_empresa_id
            FROM empresaservicio
            WHERE departamento_id IS NOT NULL
            AND id_rubro_id IS NOT NULL
            AND id_usuario_id IS NOT NULL
            AND tipo_empresa_id IS NOT NULL
        """)
        
        # 4. Obtener el siguiente ID disponible para mixtas
        cursor.execute("SELECT COALESCE(MAX(id), 0) FROM empresa")
        max_id = cursor.fetchone()[0]
        
        # 5. Copiar empresas mixtas (con nuevos IDs únicos)
        cursor.execute(f"""
            INSERT INTO empresa (
                id, fecha_creacion, fecha_actualizacion, razon_social, cuit_cuil,
                direccion, geolocalizacion, telefono, correo, sitioweb,
                email_secundario, email_terciario,
                contacto_principal_nombre, contacto_principal_cargo,
                contacto_principal_telefono, contacto_principal_email,
                contacto_secundario_nombre, contacto_secundario_cargo,
                contacto_secundario_telefono, contacto_secundario_email,
                exporta, destinoexporta, tipoexporta, interes_exportar,
                importa, tipoimporta, otrasimportaciones, frecuenciaimporta,
                certificadopyme, certificacionesbool, certificaciones, certificaciones_otros,
                archivo_certificaciones, archivo_certificaciones_nombre,
                promo2idiomas, idiomas_trabaja,
                capacidadproductiva, tiempocapacidad, otracapacidad,
                redes_sociales, latitud, longitud,
                participoferianacional, feriasnacionales,
                participoferiainternacional, feriasinternacionales,
                archivo_ferias, archivo_ferias_nombre,
                observaciones, puntaje, logo, brochure, descripcion,
                tipo_empresa_valor,
                actualizado_por_id, creado_por_id,
                departamento_id, id_rubro_id, id_usuario_id,
                localidad_id, municipio_id, tipo_empresa_id
            )
            SELECT 
                (ROW_NUMBER() OVER (ORDER BY id) + {max_id}) as id,
                fecha_creacion, fecha_actualizacion, razon_social, cuit_cuil,
                direccion, geolocalizacion, telefono, correo, sitioweb,
                email_secundario, email_terciario,
                contacto_principal_nombre, contacto_principal_cargo,
                contacto_principal_telefono, contacto_principal_email,
                contacto_secundario_nombre, contacto_secundario_cargo,
                contacto_secundario_telefono, contacto_secundario_email,
                exporta, destinoexporta, tipoexporta, interes_exportar,
                importa, tipoimporta, otrasimportaciones, frecuenciaimporta,
                certificadopyme, certificacionesbool, certificaciones, certificaciones_otros,
                archivo_certificaciones, archivo_certificaciones_nombre,
                promo2idiomas, idiomas_trabaja,
                capacidadproductiva, tiempocapacidad, otracapacidad,
                redes_sociales, latitud, longitud,
                participoferianacional, feriasnacionales,
                participoferiainternacional, feriasinternacionales,
                archivo_ferias, archivo_ferias_nombre,
                observaciones, puntaje, logo, brochure, descripcion,
                'mixta' as tipo_empresa_valor,
                actualizado_por_id,
                creado_por_id,
                departamento_id, id_rubro_id, id_usuario_id,
                localidad_id, municipio_id, tipo_empresa_id
            FROM empresa_mixta
            WHERE departamento_id IS NOT NULL
            AND id_rubro_id IS NOT NULL
            AND id_usuario_id IS NOT NULL
            AND tipo_empresa_id IS NOT NULL
        """)
        
        # 6. Actualizar MatrizClasificacionExportador (solo si la tabla existe)
        cursor.execute("""
            SELECT table_name 
            FROM information_schema.tables 
            WHERE table_name = 'matrizclasificacionexportador'
        """)
        if cursor.fetchone():
            # Para productos, mantener el mismo ID
            try:
                cursor.execute("""
                    UPDATE matrizclasificacionexportador
                    SET empresa_id = empresa_producto_id
                    WHERE empresa_producto_id IS NOT NULL AND empresa_id IS NULL
                """)
            except Exception as e:
                print(f"Warning: No se pudo actualizar matriz para productos: {e}")
            
            # Para servicios, buscar por razon_social y tipo
            try:
                cursor.execute("""
                    UPDATE matrizclasificacionexportador m
                    SET empresa_id = (
                        SELECT e.id 
                        FROM empresa e 
                        INNER JOIN empresaservicio es ON es.razon_social = e.razon_social
                        WHERE e.tipo_empresa_valor = 'servicio'
                        AND es.id = m.empresa_servicio_id
                        LIMIT 1
                    )
                    WHERE m.empresa_servicio_id IS NOT NULL AND m.empresa_id IS NULL
                """)
            except Exception as e:
                print(f"Warning: No se pudo actualizar matriz para servicios: {e}")
            
            # Para mixtas, buscar por razon_social y tipo
            try:
                cursor.execute("""
                    UPDATE matrizclasificacionexportador m
                    SET empresa_id = (
                        SELECT e.id 
                        FROM empresa e 
                        INNER JOIN empresa_mixta em ON em.razon_social = e.razon_social
                        WHERE e.tipo_empresa_valor = 'mixta'
                        AND em.id = m.empresa_mixta_id
                        LIMIT 1
                    )
                    WHERE m.empresa_mixta_id IS NOT NULL AND m.empresa_id IS NULL
                """)
            except Exception as e:
                print(f"Warning: No se pudo actualizar matriz para mixtas: {e}")
        
        # 7. Actualizar ForeignKeys de ProductoEmpresa, ServicioEmpresa, etc.
        # Para ProductoEmpresa: los IDs de productos se mantienen igual (solo si la empresa es de tipo producto)
        cursor.execute("""
            UPDATE producto_empresa pe
            SET empresa_id = (
                SELECT e.id 
                FROM empresa e 
                WHERE e.tipo_empresa_valor IN ('producto', 'mixta')
                AND e.id = pe.empresa_id
                LIMIT 1
            )
            WHERE EXISTS (
                SELECT 1 FROM empresa e WHERE e.id = pe.empresa_id AND e.tipo_empresa_valor IN ('producto', 'mixta')
            )
        """)
        
        # Para ServicioEmpresa: mapear por razon_social porque los IDs cambiaron
        # Solo actualizar si existe una correspondencia válida
        cursor.execute("""
            UPDATE servicio_empresa se
            SET empresa_id = (
                SELECT e.id 
                FROM empresa e 
                INNER JOIN empresaservicio es ON es.razon_social = e.razon_social
                WHERE e.tipo_empresa_valor IN ('servicio', 'mixta')
                AND es.id = se.empresa_id
                LIMIT 1
            )
            WHERE EXISTS (
                SELECT 1 
                FROM empresa e 
                INNER JOIN empresaservicio es ON es.razon_social = e.razon_social
                WHERE e.tipo_empresa_valor IN ('servicio', 'mixta')
                AND es.id = se.empresa_id
            )
            AND (
                SELECT e.id 
                FROM empresa e 
                INNER JOIN empresaservicio es ON es.razon_social = e.razon_social
                WHERE e.tipo_empresa_valor IN ('servicio', 'mixta')
                AND es.id = se.empresa_id
                LIMIT 1
            ) IS NOT NULL
        """)
        
        # Para ProductoEmpresaMixta: mapear por razon_social
        cursor.execute("""
            UPDATE producto_empresa_mixta pem
            SET empresa_id = (
                SELECT e.id 
                FROM empresa e 
                INNER JOIN empresa_mixta em ON em.razon_social = e.razon_social
                WHERE e.tipo_empresa_valor = 'mixta'
                AND em.id = pem.empresa_id
                LIMIT 1
            )
            WHERE EXISTS (
                SELECT 1 
                FROM empresa e 
                INNER JOIN empresa_mixta em ON em.razon_social = e.razon_social
                WHERE e.tipo_empresa_valor = 'mixta'
                AND em.id = pem.empresa_id
            )
            AND (
                SELECT e.id 
                FROM empresa e 
                INNER JOIN empresa_mixta em ON em.razon_social = e.razon_social
                WHERE e.tipo_empresa_valor = 'mixta'
                AND em.id = pem.empresa_id
                LIMIT 1
            ) IS NOT NULL
        """)
        
        # Para ServicioEmpresaMixta: mapear por razon_social
        cursor.execute("""
            UPDATE servicio_empresa_mixta sem
            SET empresa_id = (
                SELECT e.id 
                FROM empresa e 
                INNER JOIN empresa_mixta em ON em.razon_social = e.razon_social
                WHERE e.tipo_empresa_valor = 'mixta'
                AND em.id = sem.empresa_id
                LIMIT 1
            )
            WHERE EXISTS (
                SELECT 1 
                FROM empresa e 
                INNER JOIN empresa_mixta em ON em.razon_social = e.razon_social
                WHERE e.tipo_empresa_valor = 'mixta'
                AND em.id = sem.empresa_id
            )
            AND (
                SELECT e.id 
                FROM empresa e 
                INNER JOIN empresa_mixta em ON em.razon_social = e.razon_social
                WHERE e.tipo_empresa_valor = 'mixta'
                AND em.id = sem.empresa_id
                LIMIT 1
            ) IS NOT NULL
        """)

def reverse_migracion(apps, schema_editor):
    """Reversa la migración (no implementado completamente)"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0002_unificar_empresas_completo'),
    ]

    operations = [
        migrations.RunPython(migrar_datos_empresas, reverse_migracion),
        # Actualizar ForeignKeys después de migrar datos
        migrations.AlterField(
            model_name='productoempresa',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa que ofrece este producto (debe ser tipo producto o mixta)', limit_choices_to={'tipo_empresa_valor__in': ['producto', 'mixta']}, on_delete=django.db.models.deletion.CASCADE, related_name='productos_empresa', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='productoempresamixta',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa mixta que ofrece este producto', limit_choices_to={'tipo_empresa_valor': 'mixta'}, on_delete=django.db.models.deletion.CASCADE, related_name='productos_mixta', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='servicioempresa',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa que ofrece este servicio (debe ser tipo servicio o mixta)', limit_choices_to={'tipo_empresa_valor__in': ['servicio', 'mixta']}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_empresa', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='servicioempresamixta',
            name='empresa',
            field=models.ForeignKey(help_text='Empresa mixta que ofrece este servicio', limit_choices_to={'tipo_empresa_valor': 'mixta'}, on_delete=django.db.models.deletion.CASCADE, related_name='servicios_mixta', to='empresas.empresa', verbose_name='Empresa'),
        ),
    ]
