# Generated by Django 5.2.1 on 2025-11-15 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_migrar_datos_y_actualizar_fks'),
    ]

    operations = [
        # Eliminar las tablas antiguas después de migrar los datos
        migrations.DeleteModel(
            name='Empresaproducto',
        ),
        migrations.DeleteModel(
            name='Empresaservicio',
        ),
        migrations.DeleteModel(
            name='EmpresaMixta',
        ),
    ]

