# Generated by Django 5.2.1 on 2025-11-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_remove_empresa_empresa_departa_508358_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='actividades_promocion_internacional',
            field=models.JSONField(blank=True, help_text='JSON con ferias, misiones comerciales y rondas de negocios', null=True, verbose_name='Actividades de Promoción Internacional'),
        ),
    ]
