# Generated by Django 5.2.1 on 2025-11-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_eliminar_tablas_antiguas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaMixta',
            fields=[
            ],
            options={
                'verbose_name': 'Empresa Mixta',
                'verbose_name_plural': 'Empresas Mixtas',
                'ordering': ['-fecha_creacion'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.empresa',),
        ),
        migrations.CreateModel(
            name='Empresaproducto',
            fields=[
            ],
            options={
                'verbose_name': 'Empresa de Producto',
                'verbose_name_plural': 'Empresas de Productos',
                'ordering': ['-fecha_creacion'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.empresa',),
        ),
        migrations.CreateModel(
            name='Empresaservicio',
            fields=[
            ],
            options={
                'verbose_name': 'Empresa de Servicio',
                'verbose_name_plural': 'Empresas de Servicios',
                'ordering': ['-fecha_creacion'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('empresas.empresa',),
        ),
    ]
