# Generated by Django 5.2.1 on 2025-11-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_actividades_promocion_internacional'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_postal_comercial',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal Comercial'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion_comercial',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección Comercial'),
        ),
    ]
