# Generated by Django 5.2.1 on 2025-11-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_codigo_postal_comercial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioempresa',
            name='tipo_servicio',
            field=models.CharField(choices=[('consultoria', 'Consultoría y servicios empresariales'), ('tecnologias', 'Tecnologías de la información (IT)'), ('diseno_marketing', 'Diseño y marketing'), ('capacitacion', 'Capacitación y educación online'), ('culturales_eventos', 'Servicios culturales y eventos'), ('investigacion_desarrollo', 'Investigación y desarrollo (I+D)'), ('turismo_receptivo', 'Turismo receptivo'), ('otro', 'Otro (especificar)')], max_length=150, verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='servicioempresamixta',
            name='tipo_servicio',
            field=models.CharField(choices=[('consultoria', 'Consultoría y servicios empresariales'), ('tecnologias', 'Tecnologías de la información (IT)'), ('diseno_marketing', 'Diseño y marketing'), ('capacitacion', 'Capacitación y educación online'), ('culturales_eventos', 'Servicios culturales y eventos'), ('investigacion_desarrollo', 'Investigación y desarrollo (I+D)'), ('turismo_receptivo', 'Turismo receptivo'), ('otro', 'Otro (especificar)')], max_length=150, verbose_name='Tipo de Servicio'),
        ),
    ]
