# Generated by Django 5.2.1 on 2025-11-16 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresamixta_empresaproducto_empresaservicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubRubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Sub-Rubro')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden de Visualización')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subrubros', to='empresas.rubro', verbose_name='Rubro')),
            ],
            options={
                'verbose_name': 'Sub-Rubro',
                'verbose_name_plural': 'Sub-Rubros',
                'db_table': 'subrubro',
                'ordering': ['rubro__orden', 'rubro__nombre', 'orden', 'nombre'],
            },
        ),
    ]
