# Generated by Django 5.2.1 on 2025-11-28 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_alter_servicioempresa_tipo_servicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicioempresa',
            name='forma_contratacion',
            field=models.CharField(choices=[('hora', 'Por Hora'), ('proyecto', 'Por Proyecto'), ('mensual', 'Mensual'), ('otro', 'Otro')], max_length=100, verbose_name='Forma de Contratación'),
        ),
        migrations.AlterField(
            model_name='servicioempresamixta',
            name='forma_contratacion',
            field=models.CharField(choices=[('hora', 'Por Hora'), ('proyecto', 'Por Proyecto'), ('mensual', 'Mensual'), ('otro', 'Otro')], max_length=100, verbose_name='Forma de Contratación'),
        ),
    ]
