# Generated by Django 5.2.1 on 2025-12-05 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_alter_servicioempresa_forma_contratacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='id_subrubro',
            field=models.ForeignKey(blank=True, help_text='Sub-rubro principal de la empresa (para empresas de producto o servicio único)', null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.subrubro', verbose_name='Sub-Rubro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_subrubro_producto',
            field=models.ForeignKey(blank=True, help_text='Sub-rubro para productos (solo empresas mixtas)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_producto', to='empresas.subrubro', verbose_name='Sub-Rubro de Productos'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_subrubro_servicio',
            field=models.ForeignKey(blank=True, help_text='Sub-rubro para servicios (solo empresas mixtas)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresas_servicio', to='empresas.subrubro', verbose_name='Sub-Rubro de Servicios'),
        ),
    ]
