# Generated by Django 5.2.1 on 2025-12-05 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_empresa_id_subrubro_empresa_id_subrubro_producto_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='posicionarancelaria',
            name='unique_position_per_product',
        ),
        migrations.AlterField(
            model_name='posicionarancelaria',
            name='producto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='posicion_arancelaria', to='empresas.productoempresa', verbose_name='Producto'),
        ),
    ]
