# Generated by Django 5.2.1 on 2025-12-15 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_remove_posicionarancelaria_unique_position_per_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contacto_terciario_cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo del Contacto Terciario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto_terciario_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Contacto Terciario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto_terciario_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del Contacto Terciario'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto_terciario_telefono',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono del Contacto Terciario'),
        ),
    ]
