# Generated by Django 5.2.1 on 2025-12-22 03:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_empresa_add_apellidos_contactos'),
        ('geografia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='eliminado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_eliminadas', to=settings.AUTH_USER_MODEL, verbose_name='Eliminado por'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Eliminación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contacto_secundario_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido del Contacto Secundario'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contacto_terciario_apellido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apellido del Contacto Terciario'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['eliminado'], name='empresa_elimina_7be259_idx'),
        ),
    ]
