# Generated by Django 5.2.1 on 2025-12-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_add_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoempresa',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Producto'),
        ),
        migrations.AlterField(
            model_name='productoempresamixta',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Producto'),
        ),
    ]
