# Generated by Django 5.2.1 on 2025-12-27 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_empresa_ultima_notificacion_credenciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='anos_etapa_inicial',
            field=models.IntegerField(blank=True, help_text='Cantidad de años que la empresa lleva como Etapa Inicial (0-5 puntos)', null=True, verbose_name='Años en Etapa Inicial'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='anos_exportadora',
            field=models.IntegerField(blank=True, help_text='Cantidad de años que la empresa lleva como Exportadora (12-18 puntos)', null=True, verbose_name='Años como Exportadora'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='anos_potencial_exportadora',
            field=models.IntegerField(blank=True, help_text='Cantidad de años que la empresa lleva como Potencial Exportadora (6-11 puntos)', null=True, verbose_name='Años como Potencial Exportadora'),
        ),
        migrations.AlterField(
            model_name='productoempresa',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del Producto'),
        ),
        migrations.AlterField(
            model_name='productoempresamixta',
            name='descripcion',
            field=models.TextField(verbose_name='Descripción del Producto'),
        ),
    ]
