# Generated by Django 5.2.1 on 2025-11-18 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('nombre_sistema', models.CharField(default='Sistema de Gestión de Empresas Exportadoras', max_length=200, verbose_name='Nombre del Sistema')),
                ('institucion', models.CharField(default='Dirección de Intercambio Comercial Internacional y Regional - Catamarca', max_length=200, verbose_name='Institución')),
                ('email_contacto', models.EmailField(default='contacto@catamarca.gob.ar', max_length=254, verbose_name='Email de Contacto')),
                ('telefono', models.CharField(default='+54 383 4123456', max_length=50, verbose_name='Teléfono')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_actualizados', to=settings.AUTH_USER_MODEL, verbose_name='Actualizado por')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Configuración del Sistema',
                'verbose_name_plural': 'Configuraciones del Sistema',
                'db_table': 'configuracion_sistema',
            },
        ),
    ]
