# Generated by Django 5.2.1 on 2025-11-18 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracionsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='direccion',
            field=models.CharField(default='San Martín 320, San Fernando del Valle de Catamarca', max_length=255, verbose_name='Dirección'),
        ),
    ]
