# Generated by Django 5.2.1 on 2025-11-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracionsistema_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='paises_destino',
            field=models.IntegerField(default=12, verbose_name='Países de Destino'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='valor_exportado',
            field=models.CharField(default='$2.5M', max_length=50, verbose_name='Valor Exportado'),
        ),
    ]
