# Generated by Django 5.2.1 on 2025-11-18 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_configuracionsistema_paises_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsistema',
            name='beneficio1_descripcion',
            field=models.TextField(default='Conoce tu nivel de preparación para exportar mediante nuestra matriz de clasificación', verbose_name='Beneficio 1 - Descripción'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='beneficio1_titulo',
            field=models.CharField(default='Evaluación de Perfil Exportador', max_length=200, verbose_name='Beneficio 1 - Título'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='beneficio2_descripcion',
            field=models.TextField(default='Conecta con oportunidades de exportación y participa en ferias internacionales', verbose_name='Beneficio 2 - Descripción'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='beneficio2_titulo',
            field=models.CharField(default='Acceso a Mercados Internacionales', max_length=200, verbose_name='Beneficio 2 - Título'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='beneficio3_descripcion',
            field=models.TextField(default='Recibe apoyo técnico y capacitación para mejorar tu capacidad exportadora', verbose_name='Beneficio 3 - Descripción'),
        ),
        migrations.AddField(
            model_name='configuracionsistema',
            name='beneficio3_titulo',
            field=models.CharField(default='Capacitación y Asesoramiento', max_length=200, verbose_name='Beneficio 3 - Título'),
        ),
    ]
