# Generated by Django 5.2.1 on 2025-12-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracionsistema_beneficio1_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolusuario',
            name='puede_aprobar_empresas',
            field=models.BooleanField(default=False, verbose_name='Puede Aprobar Empresas Pendientes'),
        ),
        migrations.AddField(
            model_name='rolusuario',
            name='puede_ver_configuracion',
            field=models.BooleanField(default=False, verbose_name='Puede Ver Configuración'),
        ),
        migrations.AddField(
            model_name='rolusuario',
            name='puede_ver_empresas_pendientes',
            field=models.BooleanField(default=False, verbose_name='Puede Ver Empresas Pendientes'),
        ),
        migrations.AddField(
            model_name='rolusuario',
            name='puede_ver_mapa',
            field=models.BooleanField(default=True, verbose_name='Puede Ver Mapa'),
        ),
        migrations.AddField(
            model_name='rolusuario',
            name='puede_ver_matriz',
            field=models.BooleanField(default=True, verbose_name='Puede Ver Matriz de Clasificación'),
        ),
        migrations.AddField(
            model_name='rolusuario',
            name='puede_ver_reportes',
            field=models.BooleanField(default=True, verbose_name='Puede Ver Reportes'),
        ),
        migrations.AddField(
            model_name='rolusuario',
            name='puede_ver_usuarios',
            field=models.BooleanField(default=False, verbose_name='Puede Ver Usuarios'),
        ),
    ]
