# Generated by Django 5.2.1 on 2025-12-09 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rolusuario_puede_aprobar_empresas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su contraseña en el próximo inicio de sesión (solo para empresas)', verbose_name='Debe Cambiar Contraseña'),
        ),
    ]
